# Auto-generated by generate_fake_xp_interface.py

# Type stub file generated from XP*.pyi files
# This file contains type hints for all functions, classes, and constants

from XPPython3.xp_typing import (
    XPDispatchMode,
    XPElementStyle,
    XPLMAudioBus,
    XPLMBankID,
    XPLMCameraControlDuration,
    XPLMCommandPhase,
    XPLMCursorStatus,
    XPLMDataFileType,
    XPLMDataTypeID,
    XPLMDeviceID,
    XPLMDrawingPhase,
    XPLMFlightLoopPhaseType,
    XPLMFontID,
    XPLMHostApplicationID,
    XPLMKeyFlags,
    XPLMLanguageCode,
    XPLMMapLayerType,
    XPLMMapOrientation,
    XPLMMapStyle,
    XPLMMenuCheck,
    XPLMMouseStatus,
    XPLMNavFlightPlan,
    XPLMNavType,
    XPLMProbeResult,
    XPLMProbeType,
    XPLMTextureID,
    XPLMWindowDecoration,
    XPLMWindowID,
    XPLMWindowLayer,
    XPLMWindowPositioningMode,
    XPTrackStyle,
    XPWidgetClass,
    XPWidgetMessage,
    XPWidgetPropertyID,
    XPWindowStyle
)

# Constants
AircraftCarrier: int
AudioExteriorAircraft: XPLMAudioBus
AudioExteriorEnvironment: XPLMAudioBus
AudioExteriorUnprocessed: XPLMAudioBus
AudioGround: XPLMAudioBus
AudioInterior: XPLMAudioBus
AudioRadioCom1: XPLMAudioBus
AudioRadioCom2: XPLMAudioBus
AudioRadioCopilot: XPLMAudioBus
AudioRadioPilot: XPLMAudioBus
AudioUI: XPLMAudioBus
Building: int
ButtonBehaviorCheckBox: int
ButtonBehaviorPushButton: int
ButtonBehaviorRadioButton: int
CommandBegin: XPLMCommandPhase
CommandContinue: XPLMCommandPhase
CommandEnd: XPLMCommandPhase
ControlCameraForever: XPLMCameraControlDuration
ControlCameraUntilViewChanges: XPLMCameraControlDuration
ControlFlag: XPLMKeyFlags
CoolingTower: int
CursorArrow: XPLMCursorStatus
CursorButton: XPLMCursorStatus
CursorCustom: XPLMCursorStatus
CursorDefault: XPLMCursorStatus
CursorDown: XPLMCursorStatus
CursorFourArrows: XPLMCursorStatus
CursorHandle: XPLMCursorStatus
CursorHidden: XPLMCursorStatus
CursorLeft: XPLMCursorStatus
CursorLeftRight: XPLMCursorStatus
CursorRight: XPLMCursorStatus
CursorRotateLarge: XPLMCursorStatus
CursorRotateLargeLeft: XPLMCursorStatus
CursorRotateLargeRight: XPLMCursorStatus
CursorRotateMedium: XPLMCursorStatus
CursorRotateMediumLeft: XPLMCursorStatus
CursorRotateMediumRight: XPLMCursorStatus
CursorRotateSmall: XPLMCursorStatus
CursorRotateSmallLeft: XPLMCursorStatus
CursorRotateSmallRight: XPLMCursorStatus
CursorSplitterH: XPLMCursorStatus
CursorSplitterV: XPLMCursorStatus
CursorText: XPLMCursorStatus
CursorUp: XPLMCursorStatus
CursorUpDown: XPLMCursorStatus
CustomObject: int
DataFile_ReplayMovie: XPLMDataFileType
DataFile_Situation: XPLMDataFileType
DefaultWxrLimitMslFt: int
DefaultWxrRadiusNm: int
Device_CDU739_1: XPLMDeviceID
Device_CDU739_2: XPLMDeviceID
Device_CDU815_1: XPLMDeviceID
Device_CDU815_2: XPLMDeviceID
Device_G1000_MFD: XPLMDeviceID
Device_G1000_PFD_1: XPLMDeviceID
Device_G1000_PFD_2: XPLMDeviceID
Device_GNS430_1: XPLMDeviceID
Device_GNS430_2: XPLMDeviceID
Device_GNS530_1: XPLMDeviceID
Device_GNS530_2: XPLMDeviceID
Device_MCDU_1: XPLMDeviceID
Device_MCDU_2: XPLMDeviceID
Device_Primus_MFD_1: XPLMDeviceID
Device_Primus_MFD_2: XPLMDeviceID
Device_Primus_MFD_3: XPLMDeviceID
Device_Primus_PFD_1: XPLMDeviceID
Device_Primus_PFD_2: XPLMDeviceID
Device_Primus_RMU_1: XPLMDeviceID
Device_Primus_RMU_2: XPLMDeviceID
DownFlag: XPLMKeyFlags
Element_AircraftCarrier: XPElementStyle
Element_Airport: XPElementStyle
Element_Building: XPElementStyle
Element_CheckBox: XPElementStyle
Element_CheckBoxLit: XPElementStyle
Element_CoolingTower: XPElementStyle
Element_CopyButtons: XPElementStyle
Element_CopyButtonsWithEditingGrid: XPElementStyle
Element_CustomObject: XPElementStyle
Element_EditingGrid: XPElementStyle
Element_Fire: XPElementStyle
Element_ILSGlideScope: XPElementStyle
Element_LittleDownArrow: XPElementStyle
Element_LittleUpArrow: XPElementStyle
Element_MarkerLeft: XPElementStyle
Element_MarkerRight: XPElementStyle
Element_NDB: XPElementStyle
Element_OilPlatform: XPElementStyle
Element_OilPlatformSmall: XPElementStyle
Element_PowerLine: XPElementStyle
Element_PushButton: XPElementStyle
Element_PushButtonLit: XPElementStyle
Element_RadioTower: XPElementStyle
Element_ScrollBar: XPElementStyle
Element_Ship: XPElementStyle
Element_SmokeStack: XPElementStyle
Element_TextField: XPElementStyle
Element_TextFieldMiddle: XPElementStyle
Element_VOR: XPElementStyle
Element_VORWithCompassRose: XPElementStyle
Element_Waypoint: XPElementStyle
Element_WindowCloseBox: XPElementStyle
Element_WindowCloseBoxPressed: XPElementStyle
Element_WindowDragBar: XPElementStyle
Element_WindowDragBarSmooth: XPElementStyle
Element_Zoomer: XPElementStyle
FMOD_OK: int
FMOD_SOUND_FORMAT_PCM16: int
Fire: int
FlightLoop_Phase_AfterFlightModel: XPLMFlightLoopPhaseType
FlightLoop_Phase_BeforeFlightModel: XPLMFlightLoopPhaseType
Font_Basic: XPLMFontID
Font_Proportional: XPLMFontID
Fpl_CoPilot_Approach: XPLMNavFlightPlan
Fpl_CoPilot_Primary: XPLMNavFlightPlan
Fpl_CoPilot_Temporary: XPLMNavFlightPlan
Fpl_Pilot_Approach: XPLMNavFlightPlan
Fpl_Pilot_Primary: XPLMNavFlightPlan
Fpl_Pilot_Temporary: XPLMNavFlightPlan
Host_Unknown: XPLMHostApplicationID
Host_XPlane: XPLMHostApplicationID
ILSGlideScope: int
INTERNALPLUGINSPATH: str
KEY_0: int
KEY_1: int
KEY_2: int
KEY_3: int
KEY_4: int
KEY_5: int
KEY_6: int
KEY_7: int
KEY_8: int
KEY_9: int
KEY_DECIMAL: int
KEY_DELETE: int
KEY_DOWN: int
KEY_ESCAPE: int
KEY_LEFT: int
KEY_RETURN: int
KEY_RIGHT: int
KEY_TAB: int
KEY_UP: int
Language_Chinese: XPLMLanguageCode
Language_English: XPLMLanguageCode
Language_French: XPLMLanguageCode
Language_German: XPLMLanguageCode
Language_Greek: XPLMLanguageCode
Language_Italian: XPLMLanguageCode
Language_Japanese: XPLMLanguageCode
Language_Korean: XPLMLanguageCode
Language_Russian: XPLMLanguageCode
Language_Spanish: XPLMLanguageCode
Language_Ukrainian: XPLMLanguageCode
Language_Unknown: XPLMLanguageCode
LittleDownArrow: int
LittleUpArrow: int
MAP_IOS: str
MAP_USER_INTERFACE: str
MSG_AIRPLANE_COUNT_CHANGED: int
MSG_AIRPORT_LOADED: int
MSG_DATAREFS_ADDED: int
MSG_ENTERED_VR: int
MSG_EXITING_VR: int
MSG_FMOD_BANK_LOADED: int
MSG_FMOD_BANK_UNLOADING: int
MSG_LIVERY_LOADED: int
MSG_PLANE_CRASHED: int
MSG_PLANE_LOADED: int
MSG_PLANE_UNLOADED: int
MSG_RELEASE_PLANES: int
MSG_SCENERY_LOADED: int
MSG_WILL_WRITE_PREFS: int
MainWindowStyle_MainWindow: int
MainWindowStyle_Translucent: int
MapLayer_Fill: XPLMMapLayerType
MapLayer_Markings: XPLMMapLayerType
MapOrientation_Map: XPLMMapOrientation
MapOrientation_UI: XPLMMapOrientation
MapStyle_IFR_HighEnroute: XPLMMapStyle
MapStyle_IFR_LowEnroute: XPLMMapStyle
MapStyle_VFR_Sectional: XPLMMapStyle
MarkerLeft: int
MarkerRight: int
Master: XPLMAudioBus
MasterBank: XPLMBankID
Menu_Checked: XPLMMenuCheck
Menu_NoCheck: XPLMMenuCheck
Menu_Unchecked: XPLMMenuCheck
Message_CloseButtonPushed: int
Mode_Direct: XPDispatchMode
Mode_DirectAllCallbacks: XPDispatchMode
Mode_Once: XPDispatchMode
Mode_Recursive: XPDispatchMode
Mode_UpChain: XPDispatchMode
ModuleMTimes: object
MouseDown: XPLMMouseStatus
MouseDrag: XPLMMouseStatus
MouseUp: XPLMMouseStatus
MsgAirplaneCountChanged: int
MsgAirportLoaded: int
MsgDatarefsAdded: int
MsgDatarefs_Added: int
MsgEnteredVr: int
MsgExitingVr: int
MsgFmodBankLoaded: int
MsgFmodBankUnloading: int
MsgLivery_Loaded: int
MsgPlaneCrashed: int
MsgPlaneLoaded: int
MsgPlaneUnloaded: int
MsgReleasePlanes: int
MsgSceneryLoaded: int
MsgWillWritePrefs: int
Msg_AcceptChild: XPWidgetMessage
Msg_AcceptParent: XPWidgetMessage
Msg_ButtonStateChanged: int
Msg_Create: XPWidgetMessage
Msg_CursorAdjust: XPWidgetMessage
Msg_DescriptorChanged: XPWidgetMessage
Msg_Destroy: XPWidgetMessage
Msg_Draw: XPWidgetMessage
Msg_ExposedChanged: XPWidgetMessage
Msg_Hidden: XPWidgetMessage
Msg_KeyLoseFocus: XPWidgetMessage
Msg_KeyPress: XPWidgetMessage
Msg_KeyTakeFocus: XPWidgetMessage
Msg_LoseChild: XPWidgetMessage
Msg_MouseDown: XPWidgetMessage
Msg_MouseDrag: XPWidgetMessage
Msg_MouseUp: XPWidgetMessage
Msg_MouseWheel: XPWidgetMessage
Msg_None: XPWidgetMessage
Msg_Paint: XPWidgetMessage
Msg_PropertyChanged: XPWidgetMessage
Msg_PushButtonPressed: int
Msg_Reshape: XPWidgetMessage
Msg_ScrollBarSliderPositionChanged: int
Msg_Shown: XPWidgetMessage
Msg_TextFieldChanged: int
Msg_UserStart: XPWidgetMessage
NAV_NOT_FOUND: int
NDB: int
NO_PARENT: int
NO_PLUGIN_ID: int
Nav_Airport: XPLMNavType
Nav_Any: XPLMNavType
Nav_DME: XPLMNavType
Nav_Fix: XPLMNavType
Nav_GlideSlope: XPLMNavType
Nav_ILS: XPLMNavType
Nav_InnerMarker: XPLMNavType
Nav_LatLon: XPLMNavType
Nav_Localizer: XPLMNavType
Nav_MiddleMarker: XPLMNavType
Nav_NDB: XPLMNavType
Nav_OuterMarker: XPLMNavType
Nav_TACAN: XPLMNavType
Nav_Unknown: XPLMNavType
Nav_VOR: XPLMNavType
NoFlag: XPLMKeyFlags
NumCloudLayers: int
NumTemperatureLayers: int
NumWindLayers: int
OilPlatform: int
OilPlatformSmall: int
OptionAltFlag: XPLMKeyFlags
PARAM_PARENT: int
PLUGINSPATH: str
PLUGIN_XPLANE: int
Phase_FirstCockpit: XPLMDrawingPhase
Phase_Gauges: XPLMDrawingPhase
Phase_LastCockpit: XPLMDrawingPhase
Phase_LocalMap2D: XPLMDrawingPhase
Phase_LocalMap3D: XPLMDrawingPhase
Phase_LocalMapProfile: XPLMDrawingPhase
Phase_Modern3D: XPLMDrawingPhase
Phase_Panel: XPLMDrawingPhase
Phase_Window: XPLMDrawingPhase
PowerLine: int
ProbeError: XPLMProbeResult
ProbeHitTerrain: XPLMProbeResult
ProbeMissed: XPLMProbeResult
ProbeY: XPLMProbeType
Property_ActiveEditSide: int
Property_ButtonBehavior: int
Property_ButtonState: int
Property_ButtonType: int
Property_CaptionLit: int
Property_Clip: XPWidgetPropertyID
Property_DragXOff: XPWidgetPropertyID
Property_DragYOff: XPWidgetPropertyID
Property_Dragging: XPWidgetPropertyID
Property_EditFieldSelDragStart: int
Property_EditFieldSelEnd: int
Property_EditFieldSelStart: int
Property_Enabled: XPWidgetPropertyID
Property_Font: int
Property_GeneralGraphicsType: int
Property_Hilited: XPWidgetPropertyID
Property_MainWindowHasCloseBoxes: int
Property_MainWindowType: int
Property_MaxCharacters: int
Property_Object: XPWidgetPropertyID
Property_PasswordMode: int
Property_ProgressMax: int
Property_ProgressMin: int
Property_ProgressPosition: int
Property_Refcon: XPWidgetPropertyID
Property_ScrollBarMax: int
Property_ScrollBarMin: int
Property_ScrollBarPageAmount: int
Property_ScrollBarSliderPosition: int
Property_ScrollBarSlop: int
Property_ScrollBarType: int
Property_ScrollPosition: int
Property_SubWindowType: int
Property_TextFieldType: int
Property_UserStart: XPWidgetPropertyID
PushButton: int
RadioBank: XPLMBankID
RadioButton: int
RadioTower: int
ScrollBarTypeScrollBar: int
ScrollBarTypeSlider: int
ShiftFlag: XPLMKeyFlags
Ship: int
SmokeStack: int
SubWindowStyle_ListView: int
SubWindowStyle_Screen: int
SubWindowStyle_SubWindow: int
Tex_GeneralInterface: XPLMTextureID
Tex_Radar_Copilot: XPLMTextureID
Tex_Radar_Pilot: XPLMTextureID
TextEntryField: int
TextTranslucent: int
TextTransparent: int
Track_Progress: XPTrackStyle
Track_ScrollBar: XPTrackStyle
Track_Slider: XPTrackStyle
Type_Data: XPLMDataTypeID
Type_Double: XPLMDataTypeID
Type_Float: XPLMDataTypeID
Type_FloatArray: XPLMDataTypeID
Type_Int: XPLMDataTypeID
Type_IntArray: XPLMDataTypeID
Type_Unknown: XPLMDataTypeID
USER_AIRCRAFT: int
Init_Success: int
Init_Invalid: int
Init_MissingAircraft: int
Init_MissingLivery: int
Init_MissingAirport: int
Init_MissingRamp: int
Init_MissingRunway: int
UpFlag: XPLMKeyFlags
VERSION: str
VK_0: int
VK_1: int
VK_2: int
VK_3: int
VK_4: int
VK_5: int
VK_6: int
VK_7: int
VK_8: int
VK_9: int
VK_A: int
VK_ADD: int
VK_B: int
VK_BACK: int
VK_BACKQUOTE: int
VK_BACKSLASH: int
VK_C: int
VK_CLEAR: int
VK_COMMA: int
VK_D: int
VK_DECIMAL: int
VK_DELETE: int
VK_DIVIDE: int
VK_DOWN: int
VK_E: int
VK_END: int
VK_ENTER: int
VK_EQUAL: int
VK_ESCAPE: int
VK_EXECUTE: int
VK_F10: int
VK_F11: int
VK_F12: int
VK_F13: int
VK_F14: int
VK_F15: int
VK_F16: int
VK_F17: int
VK_F18: int
VK_F19: int
VK_F1: int
VK_F20: int
VK_F21: int
VK_F22: int
VK_F23: int
VK_F24: int
VK_F2: int
VK_F3: int
VK_F4: int
VK_F5: int
VK_F6: int
VK_F7: int
VK_F8: int
VK_F9: int
VK_F: int
VK_G: int
VK_H: int
VK_HELP: int
VK_HOME: int
VK_I: int
VK_INSERT: int
VK_J: int
VK_K: int
VK_L: int
VK_LBRACE: int
VK_LEFT: int
VK_M: int
VK_MINUS: int
VK_MULTIPLY: int
VK_N: int
VK_NEXT: int
VK_NUMPAD0: int
VK_NUMPAD1: int
VK_NUMPAD2: int
VK_NUMPAD3: int
VK_NUMPAD4: int
VK_NUMPAD5: int
VK_NUMPAD6: int
VK_NUMPAD7: int
VK_NUMPAD8: int
VK_NUMPAD9: int
VK_NUMPAD_ENT: int
VK_NUMPAD_EQ: int
VK_O: int
VK_P: int
VK_PERIOD: int
VK_PRINT: int
VK_PRIOR: int
VK_Q: int
VK_QUOTE: int
VK_R: int
VK_RBRACE: int
VK_RETURN: int
VK_RIGHT: int
VK_S: int
VK_SELECT: int
VK_SEMICOLON: int
VK_SEPARATOR: int
VK_SLASH: int
VK_SNAPSHOT: int
VK_SPACE: int
VK_SUBTRACT: int
VK_T: int
VK_TAB: int
VK_U: int
VK_UP: int
VK_V: int
VK_W: int
VK_X: int
VK_Y: int
VK_Z: int
VOR: int
VORWithCompassRose: int
WayPoint: int
WidgetClass_Button: XPWidgetClass
WidgetClass_Caption: XPWidgetClass
WidgetClass_GeneralGraphics: XPWidgetClass
WidgetClass_MainWindow: XPWidgetClass
WidgetClass_None: int
WidgetClass_Progress: XPWidgetClass
WidgetClass_ScrollBar: XPWidgetClass
WidgetClass_SubWindow: XPWidgetClass
WidgetClass_TextField: XPWidgetClass
WindUndefinedLayer: int
WindowCenterOnMonitor: XPLMWindowPositioningMode
WindowCloseBox: int
WindowDecorationNone: XPLMWindowDecoration
WindowDecorationRoundRectangle: XPLMWindowDecoration
WindowDecorationSelfDecorated: XPLMWindowDecoration
WindowDecorationSelfDecoratedResizable: XPLMWindowDecoration
WindowFullScreenOnAllMonitors: XPLMWindowPositioningMode
WindowFullScreenOnMonitor: XPLMWindowPositioningMode
WindowLayerFlightOverlay: XPLMWindowLayer
WindowLayerFloatingWindows: XPLMWindowLayer
WindowLayerGrowlNotifications: XPLMWindowLayer
WindowLayerModal: XPLMWindowLayer
WindowPopOut: XPLMWindowPositioningMode
WindowPositionFree: XPLMWindowPositioningMode
WindowVR: XPLMWindowPositioningMode
Window_Help: XPWindowStyle
Window_ListView: XPWindowStyle
Window_MainWindow: XPWindowStyle
Window_Screen: XPWindowStyle
Window_SubWindow: XPWindowStyle
_Airport: int
kVersion: int
kXPLM_Version: int
pythonDebugLevel: int
pythonExecutable: str

# Functions

from pathlib import Path
from simless.libs.dataref import DataRefManager
from simless.libs.dataref_viewer import DataRefCache
from simless.libs.fake_xp_menu import MenuManager
from simless.libs.fake_xp_types import CommandCallback, XPWidgetCallback
from simless.libs.flightloop import FlightLoop
from simless.libs.graphics import GraphicsManager
from simless.libs.input import InputManager
from simless.libs.widget import WidgetManager
from simless.libs.window import WindowManager
from typing import Any, Callable, List, Literal, MutableSequence, Optional, Sequence, Tuple
from xp_typing import XPLMCommandPhase, XPLMCommandRef, XPLMCursorStatus, XPLMDataRef, XPLMDataRefInfo_t, \
    XPLMDataTypeID, XPLMFlightLoopID, XPLMFlightLoopPhaseType, XPLMFontID, XPLMMenuCheck, XPLMMenuID, XPLMMouseStatus, \
    XPLMPluginID, XPWidgetClass, XPWidgetID, XPWidgetMessage, XPWidgetPropertyID
from simless.libs.plugin_runner import SimlessRunner


class FakeXP:
    """Simless xp.* façade (auto-generated)."""

    enable_gui: bool
    terminal_logging: bool
    debug_logging: bool

    enable_dataref_bridge: bool
    bridge_host: str
    bridge_port: int

    simless_runner: SimlessRunner
    window_manager: WindowManager
    graphics_manager: GraphicsManager
    input_manager: InputManager
    widget_manager: WidgetManager
    dataref_manager: DataRefManager
    menu_manager: MenuManager
    dataref_cache: DataRefCache

    def __init__(
            self,
            enable_dataref_bridge: bool = False,
            bridge_host: Optional[str] = None,
            bridge_port: Optional[int] = None,
            enable_gui: bool = True,
            terminal_logging: bool = False,
            debug_logging: bool = False,
    ) -> None: ...

    _xplane_root: Path
    _sim_log: Path
    _xpp_log: Path
    _dataref_cache_path: Path

    def _init_flightloop(self) -> None: ...

    def _init_utilities(self) -> None: ...

    AircraftCarrier: int
    AudioExteriorAircraft: XPLMAudioBus
    AudioExteriorEnvironment: XPLMAudioBus
    AudioExteriorUnprocessed: XPLMAudioBus
    AudioGround: XPLMAudioBus
    AudioInterior: XPLMAudioBus
    AudioRadioCom1: XPLMAudioBus
    AudioRadioCom2: XPLMAudioBus
    AudioRadioCopilot: XPLMAudioBus
    AudioRadioPilot: XPLMAudioBus
    AudioUI: XPLMAudioBus
    Building: int
    ButtonBehaviorCheckBox: int
    ButtonBehaviorPushButton: int
    ButtonBehaviorRadioButton: int
    CommandBegin: XPLMCommandPhase
    CommandContinue: XPLMCommandPhase
    CommandEnd: XPLMCommandPhase
    ControlCameraForever: XPLMCameraControlDuration
    ControlCameraUntilViewChanges: XPLMCameraControlDuration
    ControlFlag: XPLMKeyFlags
    CoolingTower: int
    CursorArrow: XPLMCursorStatus
    CursorButton: XPLMCursorStatus
    CursorCustom: XPLMCursorStatus
    CursorDefault: XPLMCursorStatus
    CursorDown: XPLMCursorStatus
    CursorFourArrows: XPLMCursorStatus
    CursorHandle: XPLMCursorStatus
    CursorHidden: XPLMCursorStatus
    CursorLeft: XPLMCursorStatus
    CursorLeftRight: XPLMCursorStatus
    CursorRight: XPLMCursorStatus
    CursorRotateLarge: XPLMCursorStatus
    CursorRotateLargeLeft: XPLMCursorStatus
    CursorRotateLargeRight: XPLMCursorStatus
    CursorRotateMedium: XPLMCursorStatus
    CursorRotateMediumLeft: XPLMCursorStatus
    CursorRotateMediumRight: XPLMCursorStatus
    CursorRotateSmall: XPLMCursorStatus
    CursorRotateSmallLeft: XPLMCursorStatus
    CursorRotateSmallRight: XPLMCursorStatus
    CursorSplitterH: XPLMCursorStatus
    CursorSplitterV: XPLMCursorStatus
    CursorText: XPLMCursorStatus
    CursorUp: XPLMCursorStatus
    CursorUpDown: XPLMCursorStatus
    CustomObject: int
    DataFile_ReplayMovie: XPLMDataFileType
    DataFile_Situation: XPLMDataFileType
    DefaultWxrLimitMslFt: int
    DefaultWxrRadiusNm: int
    Device_CDU739_1: XPLMDeviceID
    Device_CDU739_2: XPLMDeviceID
    Device_CDU815_1: XPLMDeviceID
    Device_CDU815_2: XPLMDeviceID
    Device_G1000_MFD: XPLMDeviceID
    Device_G1000_PFD_1: XPLMDeviceID
    Device_G1000_PFD_2: XPLMDeviceID
    Device_GNS430_1: XPLMDeviceID
    Device_GNS430_2: XPLMDeviceID
    Device_GNS530_1: XPLMDeviceID
    Device_GNS530_2: XPLMDeviceID
    Device_MCDU_1: XPLMDeviceID
    Device_MCDU_2: XPLMDeviceID
    Device_Primus_MFD_1: XPLMDeviceID
    Device_Primus_MFD_2: XPLMDeviceID
    Device_Primus_MFD_3: XPLMDeviceID
    Device_Primus_PFD_1: XPLMDeviceID
    Device_Primus_PFD_2: XPLMDeviceID
    Device_Primus_RMU_1: XPLMDeviceID
    Device_Primus_RMU_2: XPLMDeviceID
    DownFlag: XPLMKeyFlags
    Element_AircraftCarrier: XPElementStyle
    Element_Airport: XPElementStyle
    Element_Building: XPElementStyle
    Element_CheckBox: XPElementStyle
    Element_CheckBoxLit: XPElementStyle
    Element_CoolingTower: XPElementStyle
    Element_CopyButtons: XPElementStyle
    Element_CopyButtonsWithEditingGrid: XPElementStyle
    Element_CustomObject: XPElementStyle
    Element_EditingGrid: XPElementStyle
    Element_Fire: XPElementStyle
    Element_ILSGlideScope: XPElementStyle
    Element_LittleDownArrow: XPElementStyle
    Element_LittleUpArrow: XPElementStyle
    Element_MarkerLeft: XPElementStyle
    Element_MarkerRight: XPElementStyle
    Element_NDB: XPElementStyle
    Element_OilPlatform: XPElementStyle
    Element_OilPlatformSmall: XPElementStyle
    Element_PowerLine: XPElementStyle
    Element_PushButton: XPElementStyle
    Element_PushButtonLit: XPElementStyle
    Element_RadioTower: XPElementStyle
    Element_ScrollBar: XPElementStyle
    Element_Ship: XPElementStyle
    Element_SmokeStack: XPElementStyle
    Element_TextField: XPElementStyle
    Element_TextFieldMiddle: XPElementStyle
    Element_VOR: XPElementStyle
    Element_VORWithCompassRose: XPElementStyle
    Element_Waypoint: XPElementStyle
    Element_WindowCloseBox: XPElementStyle
    Element_WindowCloseBoxPressed: XPElementStyle
    Element_WindowDragBar: XPElementStyle
    Element_WindowDragBarSmooth: XPElementStyle
    Element_Zoomer: XPElementStyle
    FMOD_OK: int
    FMOD_SOUND_FORMAT_PCM16: int
    Fire: int
    FlightLoop_Phase_AfterFlightModel: XPLMFlightLoopPhaseType
    FlightLoop_Phase_BeforeFlightModel: XPLMFlightLoopPhaseType
    Font_Basic: XPLMFontID
    Font_Proportional: XPLMFontID
    Fpl_CoPilot_Approach: XPLMNavFlightPlan
    Fpl_CoPilot_Primary: XPLMNavFlightPlan
    Fpl_CoPilot_Temporary: XPLMNavFlightPlan
    Fpl_Pilot_Approach: XPLMNavFlightPlan
    Fpl_Pilot_Primary: XPLMNavFlightPlan
    Fpl_Pilot_Temporary: XPLMNavFlightPlan
    Host_Unknown: XPLMHostApplicationID
    Host_XPlane: XPLMHostApplicationID
    ILSGlideScope: int
    INTERNALPLUGINSPATH: str
    KEY_0: int
    KEY_1: int
    KEY_2: int
    KEY_3: int
    KEY_4: int
    KEY_5: int
    KEY_6: int
    KEY_7: int
    KEY_8: int
    KEY_9: int
    KEY_DECIMAL: int
    KEY_DELETE: int
    KEY_DOWN: int
    KEY_ESCAPE: int
    KEY_LEFT: int
    KEY_RETURN: int
    KEY_RIGHT: int
    KEY_TAB: int
    KEY_UP: int
    Language_Chinese: XPLMLanguageCode
    Language_English: XPLMLanguageCode
    Language_French: XPLMLanguageCode
    Language_German: XPLMLanguageCode
    Language_Greek: XPLMLanguageCode
    Language_Italian: XPLMLanguageCode
    Language_Japanese: XPLMLanguageCode
    Language_Korean: XPLMLanguageCode
    Language_Russian: XPLMLanguageCode
    Language_Spanish: XPLMLanguageCode
    Language_Ukrainian: XPLMLanguageCode
    Language_Unknown: XPLMLanguageCode
    LittleDownArrow: int
    LittleUpArrow: int
    MAP_IOS: str
    MAP_USER_INTERFACE: str
    MSG_AIRPLANE_COUNT_CHANGED: int
    MSG_AIRPORT_LOADED: int
    MSG_DATAREFS_ADDED: int
    MSG_ENTERED_VR: int
    MSG_EXITING_VR: int
    MSG_FMOD_BANK_LOADED: int
    MSG_FMOD_BANK_UNLOADING: int
    MSG_LIVERY_LOADED: int
    MSG_PLANE_CRASHED: int
    MSG_PLANE_LOADED: int
    MSG_PLANE_UNLOADED: int
    MSG_RELEASE_PLANES: int
    MSG_SCENERY_LOADED: int
    MSG_WILL_WRITE_PREFS: int
    MainWindowStyle_MainWindow: int
    MainWindowStyle_Translucent: int
    MapLayer_Fill: XPLMMapLayerType
    MapLayer_Markings: XPLMMapLayerType
    MapOrientation_Map: XPLMMapOrientation
    MapOrientation_UI: XPLMMapOrientation
    MapStyle_IFR_HighEnroute: XPLMMapStyle
    MapStyle_IFR_LowEnroute: XPLMMapStyle
    MapStyle_VFR_Sectional: XPLMMapStyle
    MarkerLeft: int
    MarkerRight: int
    Master: XPLMAudioBus
    MasterBank: XPLMBankID
    Menu_Checked: XPLMMenuCheck
    Menu_NoCheck: XPLMMenuCheck
    Menu_Unchecked: XPLMMenuCheck
    Message_CloseButtonPushed: int
    Mode_Direct: XPDispatchMode
    Mode_DirectAllCallbacks: XPDispatchMode
    Mode_Once: XPDispatchMode
    Mode_Recursive: XPDispatchMode
    Mode_UpChain: XPDispatchMode
    ModuleMTimes: object
    MouseDown: XPLMMouseStatus
    MouseDrag: XPLMMouseStatus
    MouseUp: XPLMMouseStatus
    MsgAirplaneCountChanged: int
    MsgAirportLoaded: int
    MsgDatarefsAdded: int
    MsgDatarefs_Added: int
    MsgEnteredVr: int
    MsgExitingVr: int
    MsgFmodBankLoaded: int
    MsgFmodBankUnloading: int
    MsgLivery_Loaded: int
    MsgPlaneCrashed: int
    MsgPlaneLoaded: int
    MsgPlaneUnloaded: int
    MsgReleasePlanes: int
    MsgSceneryLoaded: int
    MsgWillWritePrefs: int
    Msg_AcceptChild: XPWidgetMessage
    Msg_AcceptParent: XPWidgetMessage
    Msg_ButtonStateChanged: int
    Msg_Create: XPWidgetMessage
    Msg_CursorAdjust: XPWidgetMessage
    Msg_DescriptorChanged: XPWidgetMessage
    Msg_Destroy: XPWidgetMessage
    Msg_Draw: XPWidgetMessage
    Msg_ExposedChanged: XPWidgetMessage
    Msg_Hidden: XPWidgetMessage
    Msg_KeyLoseFocus: XPWidgetMessage
    Msg_KeyPress: XPWidgetMessage
    Msg_KeyTakeFocus: XPWidgetMessage
    Msg_LoseChild: XPWidgetMessage
    Msg_MouseDown: XPWidgetMessage
    Msg_MouseDrag: XPWidgetMessage
    Msg_MouseUp: XPWidgetMessage
    Msg_MouseWheel: XPWidgetMessage
    Msg_None: XPWidgetMessage
    Msg_Paint: XPWidgetMessage
    Msg_PropertyChanged: XPWidgetMessage
    Msg_PushButtonPressed: int
    Msg_Reshape: XPWidgetMessage
    Msg_ScrollBarSliderPositionChanged: int
    Msg_Shown: XPWidgetMessage
    Msg_TextFieldChanged: int
    Msg_UserStart: XPWidgetMessage
    NAV_NOT_FOUND: int
    NDB: int
    NO_PARENT: int
    NO_PLUGIN_ID: int
    Nav_Airport: XPLMNavType
    Nav_Any: XPLMNavType
    Nav_DME: XPLMNavType
    Nav_Fix: XPLMNavType
    Nav_GlideSlope: XPLMNavType
    Nav_ILS: XPLMNavType
    Nav_InnerMarker: XPLMNavType
    Nav_LatLon: XPLMNavType
    Nav_Localizer: XPLMNavType
    Nav_MiddleMarker: XPLMNavType
    Nav_NDB: XPLMNavType
    Nav_OuterMarker: XPLMNavType
    Nav_TACAN: XPLMNavType
    Nav_Unknown: XPLMNavType
    Nav_VOR: XPLMNavType
    NoFlag: XPLMKeyFlags
    NumCloudLayers: int
    NumTemperatureLayers: int
    NumWindLayers: int
    OilPlatform: int
    OilPlatformSmall: int
    OptionAltFlag: XPLMKeyFlags
    PARAM_PARENT: int
    PLUGINSPATH: str
    PLUGIN_XPLANE: int
    Phase_FirstCockpit: XPLMDrawingPhase
    Phase_Gauges: XPLMDrawingPhase
    Phase_LastCockpit: XPLMDrawingPhase
    Phase_LocalMap2D: XPLMDrawingPhase
    Phase_LocalMap3D: XPLMDrawingPhase
    Phase_LocalMapProfile: XPLMDrawingPhase
    Phase_Modern3D: XPLMDrawingPhase
    Phase_Panel: XPLMDrawingPhase
    Phase_Window: XPLMDrawingPhase
    PowerLine: int
    ProbeError: XPLMProbeResult
    ProbeHitTerrain: XPLMProbeResult
    ProbeMissed: XPLMProbeResult
    ProbeY: XPLMProbeType
    Property_ActiveEditSide: int
    Property_ButtonBehavior: int
    Property_ButtonState: int
    Property_ButtonType: int
    Property_CaptionLit: int
    Property_Clip: XPWidgetPropertyID
    Property_DragXOff: XPWidgetPropertyID
    Property_DragYOff: XPWidgetPropertyID
    Property_Dragging: XPWidgetPropertyID
    Property_EditFieldSelDragStart: int
    Property_EditFieldSelEnd: int
    Property_EditFieldSelStart: int
    Property_Enabled: XPWidgetPropertyID
    Property_Font: int
    Property_GeneralGraphicsType: int
    Property_Hilited: XPWidgetPropertyID
    Property_MainWindowHasCloseBoxes: int
    Property_MainWindowType: int
    Property_MaxCharacters: int
    Property_Object: XPWidgetPropertyID
    Property_PasswordMode: int
    Property_ProgressMax: int
    Property_ProgressMin: int
    Property_ProgressPosition: int
    Property_Refcon: XPWidgetPropertyID
    Property_ScrollBarMax: int
    Property_ScrollBarMin: int
    Property_ScrollBarPageAmount: int
    Property_ScrollBarSliderPosition: int
    Property_ScrollBarSlop: int
    Property_ScrollBarType: int
    Property_ScrollPosition: int
    Property_SubWindowType: int
    Property_TextFieldType: int
    Property_UserStart: XPWidgetPropertyID
    PushButton: int
    RadioBank: XPLMBankID
    RadioButton: int
    RadioTower: int
    ScrollBarTypeScrollBar: int
    ScrollBarTypeSlider: int
    ShiftFlag: XPLMKeyFlags
    Ship: int
    SmokeStack: int
    SubWindowStyle_ListView: int
    SubWindowStyle_Screen: int
    SubWindowStyle_SubWindow: int
    Tex_GeneralInterface: XPLMTextureID
    Tex_Radar_Copilot: XPLMTextureID
    Tex_Radar_Pilot: XPLMTextureID
    TextEntryField: int
    TextTranslucent: int
    TextTransparent: int
    Track_Progress: XPTrackStyle
    Track_ScrollBar: XPTrackStyle
    Track_Slider: XPTrackStyle
    Type_Data: XPLMDataTypeID
    Type_Double: XPLMDataTypeID
    Type_Float: XPLMDataTypeID
    Type_FloatArray: XPLMDataTypeID
    Type_Int: XPLMDataTypeID
    Type_IntArray: XPLMDataTypeID
    Type_Unknown: XPLMDataTypeID
    USER_AIRCRAFT: int
    Init_Success: int
    Init_Invalid: int
    Init_MissingAircraft: int
    Init_MissingLivery: int
    Init_MissingAirport: int
    Init_MissingRamp: int
    Init_MissingRunway: int
    UpFlag: XPLMKeyFlags
    VERSION: str
    VK_0: int
    VK_1: int
    VK_2: int
    VK_3: int
    VK_4: int
    VK_5: int
    VK_6: int
    VK_7: int
    VK_8: int
    VK_9: int
    VK_A: int
    VK_ADD: int
    VK_B: int
    VK_BACK: int
    VK_BACKQUOTE: int
    VK_BACKSLASH: int
    VK_C: int
    VK_CLEAR: int
    VK_COMMA: int
    VK_D: int
    VK_DECIMAL: int
    VK_DELETE: int
    VK_DIVIDE: int
    VK_DOWN: int
    VK_E: int
    VK_END: int
    VK_ENTER: int
    VK_EQUAL: int
    VK_ESCAPE: int
    VK_EXECUTE: int
    VK_F10: int
    VK_F11: int
    VK_F12: int
    VK_F13: int
    VK_F14: int
    VK_F15: int
    VK_F16: int
    VK_F17: int
    VK_F18: int
    VK_F19: int
    VK_F1: int
    VK_F20: int
    VK_F21: int
    VK_F22: int
    VK_F23: int
    VK_F24: int
    VK_F2: int
    VK_F3: int
    VK_F4: int
    VK_F5: int
    VK_F6: int
    VK_F7: int
    VK_F8: int
    VK_F9: int
    VK_F: int
    VK_G: int
    VK_H: int
    VK_HELP: int
    VK_HOME: int
    VK_I: int
    VK_INSERT: int
    VK_J: int
    VK_K: int
    VK_L: int
    VK_LBRACE: int
    VK_LEFT: int
    VK_M: int
    VK_MINUS: int
    VK_MULTIPLY: int
    VK_N: int
    VK_NEXT: int
    VK_NUMPAD0: int
    VK_NUMPAD1: int
    VK_NUMPAD2: int
    VK_NUMPAD3: int
    VK_NUMPAD4: int
    VK_NUMPAD5: int
    VK_NUMPAD6: int
    VK_NUMPAD7: int
    VK_NUMPAD8: int
    VK_NUMPAD9: int
    VK_NUMPAD_ENT: int
    VK_NUMPAD_EQ: int
    VK_O: int
    VK_P: int
    VK_PERIOD: int
    VK_PRINT: int
    VK_PRIOR: int
    VK_Q: int
    VK_QUOTE: int
    VK_R: int
    VK_RBRACE: int
    VK_RETURN: int
    VK_RIGHT: int
    VK_S: int
    VK_SELECT: int
    VK_SEMICOLON: int
    VK_SEPARATOR: int
    VK_SLASH: int
    VK_SNAPSHOT: int
    VK_SPACE: int
    VK_SUBTRACT: int
    VK_T: int
    VK_TAB: int
    VK_U: int
    VK_UP: int
    VK_V: int
    VK_W: int
    VK_X: int
    VK_Y: int
    VK_Z: int
    VOR: int
    VORWithCompassRose: int
    WayPoint: int
    WidgetClass_Button: XPWidgetClass
    WidgetClass_Caption: XPWidgetClass
    WidgetClass_GeneralGraphics: XPWidgetClass
    WidgetClass_MainWindow: XPWidgetClass
    WidgetClass_None: int
    WidgetClass_Progress: XPWidgetClass
    WidgetClass_ScrollBar: XPWidgetClass
    WidgetClass_SubWindow: XPWidgetClass
    WidgetClass_TextField: XPWidgetClass
    WindUndefinedLayer: int
    WindowCenterOnMonitor: XPLMWindowPositioningMode
    WindowCloseBox: int
    WindowDecorationNone: XPLMWindowDecoration
    WindowDecorationRoundRectangle: XPLMWindowDecoration
    WindowDecorationSelfDecorated: XPLMWindowDecoration
    WindowDecorationSelfDecoratedResizable: XPLMWindowDecoration
    WindowFullScreenOnAllMonitors: XPLMWindowPositioningMode
    WindowFullScreenOnMonitor: XPLMWindowPositioningMode
    WindowLayerFlightOverlay: XPLMWindowLayer
    WindowLayerFloatingWindows: XPLMWindowLayer
    WindowLayerGrowlNotifications: XPLMWindowLayer
    WindowLayerModal: XPLMWindowLayer
    WindowPopOut: XPLMWindowPositioningMode
    WindowPositionFree: XPLMWindowPositioningMode
    WindowVR: XPLMWindowPositioningMode
    Window_Help: XPWindowStyle
    Window_ListView: XPWindowStyle
    Window_MainWindow: XPWindowStyle
    Window_Screen: XPWindowStyle
    Window_SubWindow: XPWindowStyle
    _Airport: int
    kVersion: int
    kXPLM_Version: int
    pythonDebugLevel: int
    pythonExecutable: str

    def all_flightloop(self) -> list[FlightLoop]: ...

    def getElapsedTime(self) -> float: ...

    def getCycleNumber(self) -> int: ...

    def createFlightLoop(self, callback: Callable[[float, float, int, Any], float],
                         phase: XPLMFlightLoopPhaseType = XPLMFlightLoopPhaseType(0),
                         refCon: Any = None, ) -> XPLMFlightLoopID | int: ...

    def destroyFlightLoop(self, fid: int) -> None: ...

    def scheduleFlightLoop(self, flightLoopID: XPLMFlightLoopID, interval: float = 0.0,
                           relativeToNow: int = 1, ) -> None: ...

    def isFlightLoopValid(self, flightLoopID: XPLMFlightLoopID) -> bool: ...

    def registerFlightLoopCallback(self, callback: Callable[[float, float, int, Any], float], interval: float = 0.0,
                                   refCon: Any = None) -> None: ...

    def unregisterFlightLoopCallback(self, callback: Callable[[float, float, int, Any], float],
                                     refCon: Any = None) -> None: ...

    def setFlightLoopCallbackInterval(self, callback: Callable[[float, float, int, Any], float], interval: float = 0.0,
                                      relativeToNow: int = 1, refCon: Any = None) -> None: ...

    def speakString(self, text: str) -> None: ...

    def getSystemPath(self) -> str: ...

    def getPrefsPath(self) -> str: ...

    def getDirectorySeparator(self) -> str: ...

    def createCommand(self, name: str, description: Optional[str] = None) -> XPLMCommandRef: ...

    def findCommand(self, name: str) -> Optional[XPLMCommandRef]: ...

    def registerCommandHandler(self, commandRef: XPLMCommandRef, callback: CommandCallback, before: int = 1,
                               refCon: Any = None, ) -> None: ...

    def unregisterCommandHandler(self, commandRef: XPLMCommandRef, callback: CommandCallback, before: int,
                                 refCon: Any, ) -> None: ...

    def commandBegin(self, commandRef: XPLMCommandRef) -> None: ...

    def commandEnd(self, commandRef: XPLMCommandRef) -> None: ...

    def commandOnce(self, commandRef: XPLMCommandRef) -> None: ...

    def findDataRef(self, name: str) -> Optional[XPLMDataRef]: ...

    def getDataRefTypes(self, dataRef: XPLMDataRef) -> XPLMDataTypeID | int: ...

    def getDataRefInfo(self, dataRef: XPLMDataRef) -> XPLMDataRefInfo_t: ...

    def canWriteDataRef(self, dataRef: XPLMDataRef) -> bool: ...

    def isDataRefGood(self, dataRef: XPLMDataRef) -> bool: ...

    def getDatai(self, dr: XPLMDataRef) -> int: ...

    def getDataf(self, dr: XPLMDataRef) -> float: ...

    def getDatad(self, dr: XPLMDataRef) -> float: ...

    def getDatavi(self, dr: XPLMDataRef, values: Optional[List[int]] = None, offset: int = 0,
                  count: int = -1) -> int: ...

    def getDatavf(self, dr: XPLMDataRef, values: Optional[List[float]] = None, offset: int = 0,
                  count: int = -1) -> int: ...

    def getDatab(self, dr: XPLMDataRef, values: Optional[List[int]] = None, offset: int = 0,
                 count: int = -1) -> int: ...

    def setDatai(self, dr: XPLMDataRef, v: int) -> None: ...

    def setDataf(self, dr: XPLMDataRef, v: float) -> None: ...

    def setDatad(self, dr: XPLMDataRef, v: float) -> None: ...

    def setDatavi(self, dr: XPLMDataRef, values: Sequence[int], offset: int = 0, count: int = -1) -> int: ...

    def setDatavf(self, dr: XPLMDataRef, values: Sequence[float], offset: int = 0, count: int = -1) -> int: ...

    def setDatab(self, dr: XPLMDataRef, values: Sequence[int], offset: int = 0, count: int = -1) -> int: ...

    def getDatas(self, dr: XPLMDataRef, offset: int = 0, count: int = -1) -> str: ...

    def setDatas(self, dr: XPLMDataRef, value: str, offset: int = 0, count: int = -1) -> None: ...

    def registerDataAccessor(self, name: str, dataType: int = 0, writable: int = -1,
                             readInt: Optional[Callable[[Any], int]] = None,
                             writeInt: Optional[Callable[[Any, int], None]] = None,
                             readFloat: Optional[Callable[[Any], float]] = None,
                             writeFloat: Optional[Callable[[Any, float], None]] = None,
                             readDouble: Optional[Callable[[Any], float]] = None,
                             writeDouble: Optional[Callable[[Any, float], None]] = None,
                             readIntArray: Optional[Callable[[Any, MutableSequence[int], int, int], int]] = None,
                             writeIntArray: Optional[Callable[[Any, Sequence[int], int, int], None]] = None,
                             readFloatArray: Optional[Callable[[Any, MutableSequence[float], int, int], int]] = None,
                             writeFloatArray: Optional[Callable[[Any, Sequence[float], int, int], None]] = None,
                             readData: Optional[Callable[[Any, bytearray, int, int], int]] = None,
                             writeData: Optional[Callable[[Any, Sequence[int], int, int], None]] = None,
                             readRefCon: Optional[Any] = None, writeRefCon: Optional[Any] = None, ) -> XPLMDataRef: ...

    def unregisterDataAccessor(self, dataRef: XPLMDataRef) -> None: ...

    def createWidget(self, left: int, top: int, right: int, bottom: int, visible: int, descriptor: str, isRoot: int,
                     container: XPWidgetID | Literal[0], widgetClass: XPWidgetClass, ) -> XPWidgetID: ...

    def destroyWidget(self, wid: XPWidgetID, destroy_children: int = 1) -> None: ...

    def setWidgetGeometry(self, wid: XPWidgetID, left: int, top: int, right: int, bottom: int, ) -> None: ...

    def getWidgetGeometry(self, wid: XPWidgetID) -> tuple[int, int, int, int]: ...

    def getWidgetExposedGeometry(self, wid: XPWidgetID) -> tuple[int, int, int, int]: ...

    def showWidget(self, wid: XPWidgetID) -> None: ...

    def hideWidget(self, wid: XPWidgetID) -> None: ...

    def isWidgetVisible(self, wid: XPWidgetID) -> bool: ...

    def setWidgetProperty(self, wid: XPWidgetID, prop: XPWidgetPropertyID | int, value: Any, ) -> None: ...

    def getWidgetProperty(self, widgetID: XPWidgetID, propertyID: XPWidgetPropertyID | int,
                          exists: Optional[int] = None) -> Any: ...

    def addWidgetCallback(self, wid: XPWidgetID, callback: XPWidgetCallback) -> None: ...

    def sendMessageToWidget(self, wid: XPWidgetID, msg: XPWidgetMessage | int, param1: Any, param2: Any, ) -> None: ...

    def broadcastMessageToWidget(self, wid: XPWidgetID, msg: XPWidgetMessage | int, param1: Any,
                                 param2: Any, ) -> None: ...

    def getParentWidget(self, wid: XPWidgetID) -> XPWidgetID | None: ...

    def getWidgetForLocation(self, wid: XPWidgetID, x: int, y: int, recursive: int, ) -> Optional[XPWidgetID]: ...

    def isWidgetInFront(self, wid: XPWidgetID) -> bool: ...

    def bringWidgetToFront(self, wid: XPWidgetID) -> None: ...

    def pushWidgetBehind(self, wid: XPWidgetID) -> None: ...

    def getKeyboardFocus(self) -> XPWidgetID | None: ...

    def setKeyboardFocus(self, wid: XPWidgetID) -> None: ...

    def loseKeyboardFocus(self, wid: XPWidgetID) -> None: ...

    def getWidgetDescriptor(self, wid: XPWidgetID) -> str: ...

    def setWidgetDescriptor(self, wid: XPWidgetID, text: str) -> None: ...

    def getWidgetClass(self, wid: XPWidgetID) -> XPWidgetClass: ...

    def getWidgetUnderlyingWindow(self, wid: XPWidgetID) -> int: ...

    def createWindowEx(self, left: int = 100, top: int = 200, right: int = 200, bottom: int = 100, visible: int = 0,
                       draw: Optional[Callable[[XPLMWindowID, Any], None]] = None,
                       click: Optional[Callable[[XPLMWindowID, int, int, XPLMMouseStatus, Any], int]] = None,
                       key: Optional[Callable[[XPLMWindowID, int, int, int, Any, int], int]] = None,
                       cursor: Optional[Callable[[XPLMWindowID, int, int, Any], XPLMCursorStatus]] = None,
                       wheel: Optional[Callable[[XPLMWindowID, int, int, int, int, Any], int]] = None,
                       refCon: Any = None, decoration: Optional[XPLMWindowDecoration] = None,
                       layer: Optional[XPLMWindowLayer] = None, rightClick: Optional[
                Callable[[XPLMWindowID, int, int, XPLMMouseStatus, Any], int]] = None, ) -> XPLMWindowID | int: ...

    def destroyWindow(self, wid: XPLMWindowID) -> None: ...

    def getWindowGeometry(self, wid: XPLMWindowID) -> None: ...

    def setWindowGeometry(self, wid, left, top, right, bottom) -> None: ...

    def getWindowRefCon(self, wid: XPLMWindowID) -> None: ...

    def setWindowRefCon(self, wid: XPLMWindowID, refCon) -> None: ...

    def takeKeyboardFocus(self, wid: XPLMWindowID) -> None: ...

    def setWindowIsVisible(self, wid: XPLMWindowID, visible: int) -> None: ...

    def getWindowIsVisible(self, wid: XPLMWindowID) -> int: ...

    def registerDrawCallback(self, cb: Callable[[int, int], Any], phase: int, wantsBefore: int, ) -> None: ...

    def unregisterDrawCallback(self, cb: Callable[[int, int], Any], phase: int, wantsBefore: int, ) -> None: ...

    def drawString(self, color, x, y, text, wordWrap, fontID) -> None: ...

    def drawNumber(self, color: Sequence[float], x: int, y: int, number: float, digits: int,
                   decimals: int, ) -> None: ...

    def setGraphicsState(self, fog: int, lighting: int, alpha: int, smooth: int, texUnits: int, texMode: int,
                         depth: int, ) -> None: ...

    def generateTextureNumbers(self, count: int) -> List[int]: ...

    def bindTexture2d(self, textureID: int, unit: int) -> None: ...

    def deleteTexture(self, textureID: int) -> None: ...

    def drawTranslucentDarkBox(self, left: int, top: int, right: int, bottom: int, ) -> None: ...

    def getScreenSize(self) -> Tuple[int, int]: ...

    def getMouseLocation(self) -> Tuple[int, int]: ...

    def getFontDimensions(self, font_id: XPLMFontID) -> tuple[int, int, int]: ...

    def measureString(self, font_id: XPLMFontID, string: str) -> float: ...

    def createMenu(self, name: Optional[str] = None, parentMenuID: Optional[XPLMMenuID] = None, parentItem: int = 0,
                   handler: Optional[Callable[[Any, Any], None]] = None, refCon: Optional[Any] = None, ) -> Optional[
        XPLMMenuID]: ...

    def appendMenuItem(self, menuID: Optional[XPLMMenuID] = None, name: str = "Item", refCon: Any = None, ) -> int: ...

    def appendMenuItemWithCommand(self, menuID: Optional[XPLMMenuID] = None, name: str = "Item",
                                  commandRef: XPLMCommandRef | None = None, ) -> int: ...

    def appendMenuSeparator(self, menuID: Optional[XPLMMenuID] = None) -> Optional[int]: ...

    def setMenuItemName(self, menuID: Optional[XPLMMenuID], index: int, name: str) -> None: ...

    def checkMenuItem(self, menuID: Optional[XPLMMenuID], index: int,
                      checked: Optional[XPLMMenuCheck] = None, ) -> None: ...

    def enableMenuItem(self, menuID: Optional[XPLMMenuID], index: int, enabled: int = 1, ) -> None: ...

    def removeMenuItem(self, menuID: Optional[XPLMMenuID], index: int) -> None: ...

    def destroyMenu(self, menuID: XPLMMenuID) -> None: ...

    def log(self, msg: str, debug: bool = False) -> None: ...

    def dbg(self, msg: str) -> None: ...

    def systemLog(self, msg: str) -> None: ...

    def sys_log(self, msg: str) -> None: ...

    def getMyID(self) -> XPLMPluginID: ...

    def disablePlugin(self, plugin_id: XPLMPluginID) -> None: ...

    def isPluginEnabled(self, plugin_id: XPLMPluginID) -> int: ...

    def findPluginBySignature(self, signature: str) -> XPLMPluginID: ...

    def findPluginByPath(self, path: str) -> XPLMPluginID: ...

    def getPluginInfo(self, plugin_id: XPLMPluginID) -> tuple[str, str, str, str]: ...

    def sendMessageToPlugin(self, pluginID: XPLMPluginID, message: int, param: Optional[Any]) -> None: ...


xp: FakeXP
