from typing import Protocol, Any, Callable


class XPWidgetAPI(Protocol):
    """Interface for the widget subsystem used by FakeXP."""

    _widgets: dict[int, Any]
    _gui_initialized: bool

    def createWidget(self, *args: Any, **kwargs: Any) -> int: ...
    def setWidgetGeometry(self, wid: int, x: int, y: int, w: int, h: int) -> None: ...
    def getWidgetGeometry(self, wid: int) -> tuple[int, int, int, int]: ...
    def showWidget(self, wid: int) -> None: ...
    def hideWidget(self, wid: int) -> None: ...
    def addWidgetCallback(self, wid: int, callback: Callable[..., None]) -> None: ...
    def sendWidgetMessage(self, wid: int, msg: int, param1: Any, param2: Any) -> None: ...

    def setWidgetProperty(self, wid: int, prop: int, value: Any) -> None: ...
    def getWidgetProperty(self, wid: int, prop: int) -> Any: ...

    def begin_frame(self) -> bool: ...
    def render_widgets(self) -> None: ...
    def end_frame(self) -> None: ...


class XPGraphicsAPI(Protocol):
    """Interface for the graphics subsystem used by FakeXP."""

    def registerDrawCallback(self, callback: Callable[[], None]) -> None: ...
    def run_draw_callbacks(self) -> None: ...
    def drawString(self, x: int, y: int, text: str) -> None: ...
    def drawNumber(self, x: int, y: int, number: float) -> None: ...


class XPUtilitiesAPI(Protocol):
    """Interface for the utilities subsystem used by FakeXP."""

    def speakString(self, text: str) -> None: ...
    def getSystemPath(self) -> str: ...
    def getPrefsPath(self) -> str: ...
    def getDirectorySeparator(self) -> str: ...


class XPPluginAPI(Protocol):
    """Interface that all FakeXP plugins must implement."""

    def XPluginStart(self) -> Any: ...
    def XPluginEnable(self) -> bool: ...
    def XPluginDisable(self) -> None: ...
    def XPluginStop(self) -> None: ...
