# Type stub file generated from XP*.pyi files
# This file contains type hints for all functions, classes, and constants

from typing import Any, Callable, Generic, Literal, NewType, Optional, Protocol, Sequence, Type, TypeVar
from XPPython3.xp_typing import (
    FMODChannel,
    FMOD_CHANNEL,
    FMOD_CHANNELGROUP,
    FMOD_STUDIO_SYSTEM,
    FMSEntryInfo,
    HotKeyInfo,
    NavAidInfo,
    PluginInfo,
    TrackMetrics,
    XPDispatchMode,
    XPElementStyle,
    XPLMAudioBus,
    XPLMAvionicsID,
    XPLMBankID,
    XPLMCameraControlDuration,
    XPLMCommandPhase,
    XPLMCommandRef,
    XPLMCursorStatus,
    XPLMDataFileType,
    XPLMDataRef,
    XPLMDataRefInfo_t,
    XPLMDataTypeID,
    XPLMDeviceID,
    XPLMDrawInfoDouble_t,
    XPLMDrawInfo_t,
    XPLMDrawingPhase,
    XPLMFlightLoopID,
    XPLMFlightLoopPhaseType,
    XPLMFontID,
    XPLMHostApplicationID,
    XPLMHotKeyID,
    XPLMInstanceRef,
    XPLMKeyFlags,
    XPLMLanguageCode,
    XPLMMapLayerID,
    XPLMMapLayerType,
    XPLMMapOrientation,
    XPLMMapProjectionID,
    XPLMMapStyle,
    XPLMMenuCheck,
    XPLMMenuID,
    XPLMMouseStatus,
    XPLMNavFlightPlan,
    XPLMNavRef,
    XPLMNavType,
    XPLMObjectRef,
    XPLMPluginID,
    XPLMProbeInfo_t,
    XPLMProbeRef,
    XPLMProbeResult,
    XPLMProbeType,
    XPLMTextureID,
    XPLMWeatherInfo_t,
    XPLMWindowDecoration,
    XPLMWindowID,
    XPLMWindowLayer,
    XPLMWindowPositioningMode,
    XPTrackStyle,
    XPWidgetClass,
    XPWidgetID,
    XPWidgetMessage,
    XPWidgetPropertyID,
    XPWindowStyle
)

# Constants
AircraftCarrier: int
AudioExteriorAircraft: XPLMAudioBus
AudioExteriorEnvironment: XPLMAudioBus
AudioExteriorUnprocessed: XPLMAudioBus
AudioGround: XPLMAudioBus
AudioInterior: XPLMAudioBus
AudioRadioCom1: XPLMAudioBus
AudioRadioCom2: XPLMAudioBus
AudioRadioCopilot: XPLMAudioBus
AudioRadioPilot: XPLMAudioBus
AudioUI: XPLMAudioBus
Building: int
ButtonBehaviorCheckBox: int
ButtonBehaviorPushButton: int
ButtonBehaviorRadioButton: int
CommandBegin: XPLMCommandPhase
CommandContinue: XPLMCommandPhase
CommandEnd: XPLMCommandPhase
ControlCameraForever: XPLMCameraControlDuration
ControlCameraUntilViewChanges: XPLMCameraControlDuration
ControlFlag: XPLMKeyFlags
CoolingTower: int
CursorArrow: XPLMCursorStatus
CursorButton: XPLMCursorStatus
CursorCustom: XPLMCursorStatus
CursorDefault: XPLMCursorStatus
CursorDown: XPLMCursorStatus
CursorFourArrows: XPLMCursorStatus
CursorHandle: XPLMCursorStatus
CursorHidden: XPLMCursorStatus
CursorLeft: XPLMCursorStatus
CursorLeftRight: XPLMCursorStatus
CursorRight: XPLMCursorStatus
CursorRotateLarge: XPLMCursorStatus
CursorRotateLargeLeft: XPLMCursorStatus
CursorRotateLargeRight: XPLMCursorStatus
CursorRotateMedium: XPLMCursorStatus
CursorRotateMediumLeft: XPLMCursorStatus
CursorRotateMediumRight: XPLMCursorStatus
CursorRotateSmall: XPLMCursorStatus
CursorRotateSmallLeft: XPLMCursorStatus
CursorRotateSmallRight: XPLMCursorStatus
CursorSplitterH: XPLMCursorStatus
CursorSplitterV: XPLMCursorStatus
CursorText: XPLMCursorStatus
CursorUp: XPLMCursorStatus
CursorUpDown: XPLMCursorStatus
CustomObject: int
DataFile_ReplayMovie: XPLMDataFileType
DataFile_Situation: XPLMDataFileType
DefaultWxrRadiusMslFt: int
DefaultWxrRadiusNm: int
Device_CDU739_1: XPLMDeviceID
Device_CDU739_2: XPLMDeviceID
Device_CDU815_1: XPLMDeviceID
Device_CDU815_2: XPLMDeviceID
Device_G1000_MFD: XPLMDeviceID
Device_G1000_PFD_1: XPLMDeviceID
Device_G1000_PFD_2: XPLMDeviceID
Device_GNS430_1: XPLMDeviceID
Device_GNS430_2: XPLMDeviceID
Device_GNS530_1: XPLMDeviceID
Device_GNS530_2: XPLMDeviceID
Device_MCDU_1: XPLMDeviceID
Device_MCDU_2: XPLMDeviceID
Device_Primus_MFD_1: XPLMDeviceID
Device_Primus_MFD_2: XPLMDeviceID
Device_Primus_MFD_3: XPLMDeviceID
Device_Primus_PFD_1: XPLMDeviceID
Device_Primus_PFD_2: XPLMDeviceID
Device_Primus_RMU_1: XPLMDeviceID
Device_Primus_RMU_2: XPLMDeviceID
DownFlag: XPLMKeyFlags
Element_AircraftCarrier: XPElementStyle
Element_Airport: XPElementStyle
Element_Building: XPElementStyle
Element_CheckBox: XPElementStyle
Element_CheckBoxLit: XPElementStyle
Element_CoolingTower: XPElementStyle
Element_CopyButtons: XPElementStyle
Element_CopyButtonsWithEditingGrid: XPElementStyle
Element_CustomObject: XPElementStyle
Element_EditingGrid: XPElementStyle
Element_Fire: XPElementStyle
Element_ILSGlideScope: XPElementStyle
Element_LittleDownArrow: XPElementStyle
Element_LittleUpArrow: XPElementStyle
Element_MarkerLeft: XPElementStyle
Element_MarkerRight: XPElementStyle
Element_NDB: XPElementStyle
Element_OilPlatform: XPElementStyle
Element_OilPlatformSmall: XPElementStyle
Element_PowerLine: XPElementStyle
Element_PushButton: XPElementStyle
Element_PushButtonLit: XPElementStyle
Element_RadioTower: XPElementStyle
Element_ScrollBar: XPElementStyle
Element_Ship: XPElementStyle
Element_SmokeStack: XPElementStyle
Element_TextField: XPElementStyle
Element_TextFieldMiddle: XPElementStyle
Element_VOR: XPElementStyle
Element_VORWithCompassRose: XPElementStyle
Element_Waypoint: XPElementStyle
Element_WindowCloseBox: XPElementStyle
Element_WindowCloseBoxPressed: XPElementStyle
Element_WindowDragBar: XPElementStyle
Element_WindowDragBarSmooth: XPElementStyle
Element_Zoomer: XPElementStyle
FMOD_OK: int
FMOD_SOUND_FORMAT_PCM16: int
Fire: int
FlightLoop_Phase_AfterFlightModel: XPLMFlightLoopPhaseType
FlightLoop_Phase_BeforeFlightModel: XPLMFlightLoopPhaseType
Font_Basic: XPLMFontID
Font_Proportional: XPLMFontID
Fpl_CoPilot_Approach: XPLMNavFlightPlan
Fpl_CoPilot_Primary: XPLMNavFlightPlan
Fpl_CoPilot_Temporary: XPLMNavFlightPlan
Fpl_Pilot_Approach: XPLMNavFlightPlan
Fpl_Pilot_Primary: XPLMNavFlightPlan
Fpl_Pilot_Temporary: XPLMNavFlightPlan
Host_Unknown: XPLMHostApplicationID
Host_XPlane: XPLMHostApplicationID
ILSGlideScope: int
INTERNALPLUGINSPATH: str
KEY_0: int
KEY_1: int
KEY_2: int
KEY_3: int
KEY_4: int
KEY_5: int
KEY_6: int
KEY_7: int
KEY_8: int
KEY_9: int
KEY_DECIMAL: int
KEY_DELETE: int
KEY_DOWN: int
KEY_ESCAPE: int
KEY_LEFT: int
KEY_RETURN: int
KEY_RIGHT: int
KEY_TAB: int
KEY_UP: int
Language_Chinese: XPLMLanguageCode
Language_English: XPLMLanguageCode
Language_French: XPLMLanguageCode
Language_German: XPLMLanguageCode
Language_Greek: XPLMLanguageCode
Language_Italian: XPLMLanguageCode
Language_Japanese: XPLMLanguageCode
Language_Korean: XPLMLanguageCode
Language_Russian: XPLMLanguageCode
Language_Spanish: XPLMLanguageCode
Language_Ukrainian: XPLMLanguageCode
Language_Unknown: XPLMLanguageCode
LittleDownArrow: int
LittleUpArrow: int
MAP_IOS: str
MAP_USER_INTERFACE: str
MSG_AIRPLANE_COUNT_CHANGED: int
MSG_AIRPORT_LOADED: int
MSG_DATAREFS_ADDED: int
MSG_ENTERED_VR: int
MSG_EXITING_VR: int
MSG_FMOD_BANK_LOADED: int
MSG_FMOD_BANK_UNLOADING: int
MSG_LIVERY_LOADED: int
MSG_PLANE_CRASHED: int
MSG_PLANE_LOADED: int
MSG_PLANE_UNLOADED: int
MSG_RELEASE_PLANES: int
MSG_SCENERY_LOADED: int
MSG_WILL_WRITE_PREFS: int
MainWindowStyle_MainWindow: int
MainWindowStyle_Translucent: int
MapLayer_Fill: XPLMMapLayerType
MapLayer_Markings: XPLMMapLayerType
MapOrientation_Map: XPLMMapOrientation
MapOrientation_UI: XPLMMapOrientation
MapStyle_IFR_HighEnroute: XPLMMapStyle
MapStyle_IFR_LowEnroute: XPLMMapStyle
MapStyle_VFR_Sectional: XPLMMapStyle
MarkerLeft: int
MarkerRight: int
Master: XPLMAudioBus
MasterBank: XPLMBankID
Menu_Checked: XPLMMenuCheck
Menu_NoCheck: XPLMMenuCheck
Menu_Unchecked: XPLMMenuCheck
Message_CloseButtonPushed: int
Mode_Direct: XPDispatchMode
Mode_DirectAllCallbacks: XPDispatchMode
Mode_Once: XPDispatchMode
Mode_Recursive: XPDispatchMode
Mode_UpChain: XPDispatchMode
ModuleMTimes: object
MouseDown: XPLMMouseStatus
MouseDrag: XPLMMouseStatus
MouseUp: XPLMMouseStatus
MsgAirplaneCountChanged: int
MsgAirportLoaded: int
MsgDatarefsAdded: int
MsgDatarefs_Added: int
MsgEnteredVr: int
MsgExitingVr: int
MsgFmodBankLoaded: int
MsgFmodBankUnloading: int
MsgLivery_Loaded: int
MsgPlaneCrashed: int
MsgPlaneLoaded: int
MsgPlaneUnloaded: int
MsgReleasePlanes: int
MsgSceneryLoaded: int
MsgWillWritePrefs: int
Msg_AcceptChild: XPWidgetMessage
Msg_AcceptParent: XPWidgetMessage
Msg_ButtonStateChanged: int
Msg_Create: XPWidgetMessage
Msg_CursorAdjust: XPWidgetMessage
Msg_DescriptorChanged: XPWidgetMessage
Msg_Destroy: XPWidgetMessage
Msg_Draw: XPWidgetMessage
Msg_ExposedChanged: XPWidgetMessage
Msg_Hidden: XPWidgetMessage
Msg_KeyLoseFocus: XPWidgetMessage
Msg_KeyPress: XPWidgetMessage
Msg_KeyTakeFocus: XPWidgetMessage
Msg_LoseChild: XPWidgetMessage
Msg_MouseDown: XPWidgetMessage
Msg_MouseDrag: XPWidgetMessage
Msg_MouseUp: XPWidgetMessage
Msg_MouseWheel: XPWidgetMessage
Msg_None: XPWidgetMessage
Msg_Paint: XPWidgetMessage
Msg_PropertyChanged: XPWidgetMessage
Msg_PushButtonPressed: int
Msg_Reshape: XPWidgetMessage
Msg_ScrollBarSliderPositionChanged: int
Msg_Shown: XPWidgetMessage
Msg_TextFieldChanged: int
Msg_UserStart: XPWidgetMessage
NAV_NOT_FOUND: int
NDB: int
NO_PARENT: int
NO_PLUGIN_ID: int
Nav_Airport: XPLMNavType
Nav_Any: XPLMNavType
Nav_DME: XPLMNavType
Nav_Fix: XPLMNavType
Nav_GlideSlope: XPLMNavType
Nav_ILS: XPLMNavType
Nav_InnerMarker: XPLMNavType
Nav_LatLon: XPLMNavType
Nav_Localizer: XPLMNavType
Nav_MiddleMarker: XPLMNavType
Nav_NDB: XPLMNavType
Nav_OuterMarker: XPLMNavType
Nav_TACAN: XPLMNavType
Nav_Unknown: XPLMNavType
Nav_VOR: XPLMNavType
NoFlag: XPLMKeyFlags
NumCloudLayers: int
NumTemperatureLayers: int
NumWindLayers: int
OilPlatform: int
OilPlatformSmall: int
OptionAltFlag: XPLMKeyFlags
PARAM_PARENT: int
PLUGINSPATH: str
PLUGIN_XPLANE: int
Phase_FirstCockpit: XPLMDrawingPhase
Phase_Gauges: XPLMDrawingPhase
Phase_LastCockpit: XPLMDrawingPhase
Phase_LocalMap2D: XPLMDrawingPhase
Phase_LocalMap3D: XPLMDrawingPhase
Phase_LocalMapProfile: XPLMDrawingPhase
Phase_Modern3D: XPLMDrawingPhase
Phase_Panel: XPLMDrawingPhase
Phase_Window: XPLMDrawingPhase
PowerLine: int
ProbeError: XPLMProbeResult
ProbeHitTerrain: XPLMProbeResult
ProbeMissed: XPLMProbeResult
ProbeY: XPLMProbeType
Property_ActiveEditSide: int
Property_ButtonBehavior: int
Property_ButtonState: int
Property_ButtonType: int
Property_CaptionLit: int
Property_Clip: XPWidgetPropertyID
Property_DragXOff: XPWidgetPropertyID
Property_DragYOff: XPWidgetPropertyID
Property_Dragging: XPWidgetPropertyID
Property_EditFieldSelDragStart: int
Property_EditFieldSelEnd: int
Property_EditFieldSelStart: int
Property_Enabled: XPWidgetPropertyID
Property_Font: int
Property_GeneralGraphicsType: int
Property_Hilited: XPWidgetPropertyID
Property_MainWindowHasCloseBoxes: int
Property_MainWindowType: int
Property_MaxCharacters: int
Property_Object: XPWidgetPropertyID
Property_PasswordMode: int
Property_ProgressMax: int
Property_ProgressMin: int
Property_ProgressPosition: int
Property_Refcon: XPWidgetPropertyID
Property_ScrollBarMax: int
Property_ScrollBarMin: int
Property_ScrollBarPageAmount: int
Property_ScrollBarSliderPosition: int
Property_ScrollBarSlop: int
Property_ScrollBarType: int
Property_ScrollPosition: int
Property_SubWindowType: int
Property_TextFieldType: int
Property_UserStart: XPWidgetPropertyID
PushButton: int
RadioBank: XPLMBankID
RadioButton: int
RadioTower: int
ScrollBarTypeScrollBar: int
ScrollBarTypeSlider: int
ShiftFlag: XPLMKeyFlags
Ship: int
SmokeStack: int
SubWindowStyle_ListView: int
SubWindowStyle_Screen: int
SubWindowStyle_SubWindow: int
Tex_GeneralInterface: XPLMTextureID
Tex_Radar_Copilot: XPLMTextureID
Tex_Radar_Pilot: XPLMTextureID
TextEntryField: int
TextTranslucent: int
TextTransparent: int
Track_Progress: XPTrackStyle
Track_ScrollBar: XPTrackStyle
Track_Slider: XPTrackStyle
Type_Data: XPLMDataTypeID
Type_Double: XPLMDataTypeID
Type_Float: XPLMDataTypeID
Type_FloatArray: XPLMDataTypeID
Type_Int: XPLMDataTypeID
Type_IntArray: XPLMDataTypeID
Type_Unknown: XPLMDataTypeID
USER_AIRCRAFT: int
UpFlag: XPLMKeyFlags
VERSION: str
VK_0: int
VK_1: int
VK_2: int
VK_3: int
VK_4: int
VK_5: int
VK_6: int
VK_7: int
VK_8: int
VK_9: int
VK_A: int
VK_ADD: int
VK_B: int
VK_BACK: int
VK_BACKQUOTE: int
VK_BACKSLASH: int
VK_C: int
VK_CLEAR: int
VK_COMMA: int
VK_D: int
VK_DECIMAL: int
VK_DELETE: int
VK_DIVIDE: int
VK_DOWN: int
VK_E: int
VK_END: int
VK_ENTER: int
VK_EQUAL: int
VK_ESCAPE: int
VK_EXECUTE: int
VK_F10: int
VK_F11: int
VK_F12: int
VK_F13: int
VK_F14: int
VK_F15: int
VK_F16: int
VK_F17: int
VK_F18: int
VK_F19: int
VK_F1: int
VK_F20: int
VK_F21: int
VK_F22: int
VK_F23: int
VK_F24: int
VK_F2: int
VK_F3: int
VK_F4: int
VK_F5: int
VK_F6: int
VK_F7: int
VK_F8: int
VK_F9: int
VK_F: int
VK_G: int
VK_H: int
VK_HELP: int
VK_HOME: int
VK_I: int
VK_INSERT: int
VK_J: int
VK_K: int
VK_L: int
VK_LBRACE: int
VK_LEFT: int
VK_M: int
VK_MINUS: int
VK_MULTIPLY: int
VK_N: int
VK_NEXT: int
VK_NUMPAD0: int
VK_NUMPAD1: int
VK_NUMPAD2: int
VK_NUMPAD3: int
VK_NUMPAD4: int
VK_NUMPAD5: int
VK_NUMPAD6: int
VK_NUMPAD7: int
VK_NUMPAD8: int
VK_NUMPAD9: int
VK_NUMPAD_ENT: int
VK_NUMPAD_EQ: int
VK_O: int
VK_P: int
VK_PERIOD: int
VK_PRINT: int
VK_PRIOR: int
VK_Q: int
VK_QUOTE: int
VK_R: int
VK_RBRACE: int
VK_RETURN: int
VK_RIGHT: int
VK_S: int
VK_SELECT: int
VK_SEMICOLON: int
VK_SEPARATOR: int
VK_SLASH: int
VK_SNAPSHOT: int
VK_SPACE: int
VK_SUBTRACT: int
VK_T: int
VK_TAB: int
VK_U: int
VK_UP: int
VK_V: int
VK_W: int
VK_X: int
VK_Y: int
VK_Z: int
VOR: int
VORWithCompassRose: int
WayPoint: int
WidgetClass_Button: XPWidgetClass
WidgetClass_Caption: XPWidgetClass
WidgetClass_GeneralGraphics: XPWidgetClass
WidgetClass_MainWindow: XPWidgetClass
WidgetClass_None: int
WidgetClass_Progress: XPWidgetClass
WidgetClass_ScrollBar: XPWidgetClass
WidgetClass_SubWindow: XPWidgetClass
WidgetClass_TextField: XPWidgetClass
WindUndefinedLayer: int
WindowCenterOnMonitor: XPLMWindowPositioningMode
WindowCloseBox: int
WindowDecorationNone: XPLMWindowDecoration
WindowDecorationRoundRectangle: XPLMWindowDecoration
WindowDecorationSelfDecorated: XPLMWindowDecoration
WindowDecorationSelfDecoratedResizable: XPLMWindowDecoration
WindowFullScreenOnAllMonitors: XPLMWindowPositioningMode
WindowFullScreenOnMonitor: XPLMWindowPositioningMode
WindowLayerFlightOverlay: XPLMWindowLayer
WindowLayerFloatingWindows: XPLMWindowLayer
WindowLayerGrowlNotifications: XPLMWindowLayer
WindowLayerModal: XPLMWindowLayer
WindowPopOut: XPLMWindowPositioningMode
WindowPositionFree: XPLMWindowPositioningMode
WindowVR: XPLMWindowPositioningMode
Window_Help: XPWindowStyle
Window_ListView: XPWindowStyle
Window_MainWindow: XPWindowStyle
Window_Screen: XPWindowStyle
Window_SubWindow: XPWindowStyle
_Airport: int
kVersion: int
kXPLM_Version: int
pythonDebugLevel: int
pythonExecutable: str

# Functions

class XPInterface(Protocol):
    def loadCursor(self, name: str) -> int: ...
    def setCursor(self, cursor_id: int) -> None: ...
    def unloadCursor(self, cursor_id: int) -> None: ...
    def controlCamera(self, howLong: int=ControlCameraUntilViewChanges, controlFunc: Optional[Callable[[list[float], int, Any], int]]=None, refCon: Any=None) -> None: ...
    def dontControlCamera(self) -> None: ...
    def isCameraBeingControlled(self) -> tuple[int, int]: ...
    def readCameraPosition(self) -> tuple[float, float, float, float, float, float, float]: ...
    def findDataRef(self, name: str) -> XPLMDataRef: ...
    def canWriteDataRef(self, dataRef: XPLMDataRef) -> bool: ...
    def isDataRefGood(self, dataRef: XPLMDataRef) -> bool: ...
    def getDataRefTypes(self, dataRef: XPLMDataRef) -> int: ...
    def getDatai(self, dataRef: XPLMDataRef) -> int: ...
    def setDatai(self, dataRef: XPLMDataRef, value: int=0) -> None: ...
    def getDataf(self, dataRef: XPLMDataRef) -> float: ...
    def setDataf(self, dataRef: XPLMDataRef, value: float=0.0) -> None: ...
    def getDatad(self, dataRef: XPLMDataRef) -> float: ...
    def setDatad(self, dataRef: XPLMDataRef, value: float=0.0) -> None: ...
    def getDatavi(self, dataRef: XPLMDataRef, values: Optional[list[int]]=None, offset: int=0, count: int=-1) -> int: ...
    def setDatavi(self, dataRef: XPLMDataRef, values: list[int], offset: int=0, count: int=-1) -> None: ...
    def getDatavf(self, dataRef: XPLMDataRef, values: Optional[list[float]]=None, offset: int=0, count: int=-1) -> int: ...
    def setDatavf(self, dataRef: XPLMDataRef, values: list[float], offset: int=0, count: int=-1) -> None: ...
    def getDatab(self, dataRef: XPLMDataRef, values: Optional[list[int]]=None, offset: int=0, count: int=-1) -> int: ...
    def setDatab(self, dataRef: XPLMDataRef, values: list[int] | bytes, offset: int=0, count: int=-1) -> None: ...
    def getDatas(self, dataRef: XPLMDataRef, offset: int=0, count: int=-1) -> str | None: ...
    def setDatas(self, dataRef: XPLMDataRef, value: str, offset: int=0, count: int=-1) -> None: ...
    def registerDataAccessor(self, name: str, dataType: int=Type_Unknown, writable: int=-1, readInt: Optional[Callable[[Any], int]]=None, writeInt: Optional[Callable[[Any, int], None]]=None, readFloat: Optional[Callable[[Any], float]]=None, writeFloat: Optional[Callable[[Any, float], None]]=None, readDouble: Optional[Callable[[Any], float]]=None, writeDouble: Optional[Callable[[Any, float], None]]=None, readIntArray: Optional[Callable[[Any, list[int], int, int], int]]=None, writeIntArray: Optional[Callable[[Any, list[int], int, int], None]]=None, readFloatArray: Optional[Callable[[Any, list[float], int, int], int]]=None, writeFloatArray: Optional[Callable[[Any, list[float], int, int], None]]=None, readData: Optional[Callable[[Any, list[int], int, int], int]]=None, writeData: Optional[Callable[[Any, list[int], int, int], None]]=None, readRefCon: Any=None, writeRefCon: Any=None) -> XPLMDataRef: ...
    def unregisterDataAccessor(self, accessor: XPLMDataRef) -> None: ...
    def shareData(self, name: str, dataType: int, dataChanged: Optional[Callable[[Any], None]]=None, refCon: Any=None) -> int: ...
    def countDataRefs(self) -> int: ...
    def getDataRefsByIndex(self, offset: int=0, count: int=1) -> None | list[XPLMDataRef]: ...
    def getDataRefInfo(self, dataRef: XPLMDataRef) -> XPLMDataRefInfo_t: ...
    def unshareData(self, name: str, dataType: int, dataChanged: Optional[Callable[[Any], None]]=None, refCon: Any=None) -> int: ...
    def getDataRefCallbackDict(self) -> dict[int, tuple[str, str, int, int, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any]]: ...
    def getSharedDataRefCallbackDict(self) -> dict[int, tuple[str, str, int, Any, Any]]: ...
    def registerDrawCallback(self, draw: Callable[[XPLMDrawingPhase, int, Any], None | int], phase: XPLMDrawingPhase=Phase_Window, after: int=0, refCon: Any=None) -> int: ...
    def registerAvionicsCallbacksEx(self, deviceId: XPLMDeviceID, before: Optional[Callable[[XPLMDeviceID, int, Any], int]]=None, after: Optional[Callable[[XPLMDeviceID, int, Any], int]]=None, refCon: Any=None, bezelClick: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, bezelRightClick: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, bezelScroll: Optional[Callable[[int, int, int, int, Any], int]]=None, bezelCursor: Optional[Callable[[int, int, Any], XPLMCursorStatus]]=None, screenTouch: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, screenRightTouch: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, screenScroll: Optional[Callable[[int, int, int, int, Any], int]]=None, screenCursor: Optional[Callable[[int, int, Any], XPLMCursorStatus]]=None, keyboard: Optional[Callable[[int, XPLMKeyFlags, int, Any, int], int]]=None) -> XPLMAvionicsID: ...
    def unregisterAvionicsCallbacks(self, avionicsId: XPLMAvionicsID) -> None: ...
    def getAvionicsHandle(self, deviceID: int) -> XPLMAvionicsID: ...
    def isAvionicsBound(self, avionicsID: XPLMAvionicsID) -> int: ...
    def isCursorOverAvionics(self, avionicsID: XPLMAvionicsID) -> tuple[int, int] | None: ...
    def isAvionicsPopupVisible(self, avionicsID: XPLMAvionicsID) -> int: ...
    def isAvionicsPoppedOut(self, avionicsID: XPLMAvionicsID) -> int: ...
    def hasAvionicsKeyboardFocus(self, avionicsID: XPLMAvionicsID) -> int: ...
    def avionicsNeedsDrawing(self, avionicsID: XPLMAvionicsID) -> None: ...
    def popOutAvionics(self, avionicsID: XPLMAvionicsID) -> None: ...
    def takeAvionicsKeyboardFocus(self, avionicsID: XPLMAvionicsID) -> None: ...
    def destroyAvionics(self, avionicsID: XPLMAvionicsID) -> None: ...
    def getAvionicsBusVoltsRatio(self, avionicsID: XPLMAvionicsID) -> float: ...
    def getAvionicsBrightnessRheo(self, avionicsID: XPLMAvionicsID) -> float: ...
    def setAvionicsBrightnessRheo(self, avionicsID: XPLMAvionicsID, brightness: float=1.0) -> None: ...
    def setAvionicsPopupVisible(self, avionicsID: XPLMAvionicsID, visible: int=1) -> None: ...
    def registerKeySniffer(self, sniffer: Callable[[int, XPLMKeyFlags, int, Any], int], before: int=0, refCon: Any=None) -> int: ...
    def unregisterDrawCallback(self, draw: Callable[[XPLMDrawingPhase, int, Any], None], phase: XPLMDrawingPhase=Phase_Window, after: int=0, refCon: Any=None) -> int: ...
    def unregisterKeySniffer(self, sniffer: Callable[[int, XPLMKeyFlags, int, Any], int], before: int=0, refCon: Any=None) -> int: ...
    def createAvionicsEx(self, screenWidth: int=100, screenHeight: int=200, bezelWidth: int=140, bezelHeight: int=250, screenOffsetX: int=20, screenOffsetY: int=25, drawOnDemand=0, bezelDraw: Optional[Callable[[float, float, float, Any], None]]=None, screenDraw: Optional[Callable[[Any], None]]=None, bezelClick: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, bezelRightClick: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, bezelScroll: Optional[Callable[[int, int, int, int, Any], int]]=None, bezelCursor: Optional[Callable[[int, int, Any], XPLMCursorStatus]]=None, screenTouch: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, screenRightTouch: Optional[Callable[[int, int, XPLMMouseStatus, Any], int]]=None, screenScroll: Optional[Callable[[int, int, int, int, Any], int]]=None, screenCursor: Optional[Callable[[int, int, Any], XPLMCursorStatus]]=None, keyboard: Optional[Callable[[int, XPLMKeyFlags, int, Any, int], int]]=None, brightness: Optional[Callable[[float, float, float, float], float]]=None, deviceID: str='deviceID', deviceName: str='deviceName', refCon: Any=None) -> XPLMAvionicsID: ...
    def createWindowEx(self, left: int=100, top: int=200, right: int=200, bottom: int=100, visible: int=0, draw: Optional[Callable[[XPLMWindowID, Any], None]]=None, click: Optional[Callable[[XPLMWindowID, int, int, XPLMMouseStatus, Any], int]]=None, key: Optional[Callable[[XPLMWindowID, int, int, int, Any, int], None]]=None, cursor: Optional[Callable[[XPLMWindowID, int, int, Any], XPLMCursorStatus]]=None, wheel: Optional[Callable[[XPLMWindowID, int, int, int, int, Any], int]]=None, refCon: Any=None, decoration: XPLMWindowDecoration=WindowDecorationRoundRectangle, layer: XPLMWindowLayer=WindowLayerFloatingWindows, rightClick: Optional[Callable[[XPLMWindowID, int, int, XPLMMouseStatus, Any], int]]=None) -> XPLMWindowID: ...
    def createWindow(self, left: int=100, top: int=200, right: int=200, bottom: int=100, visible: int=0, draw: Optional[Callable[[XPLMWindowID, Any], None]]=None, key: Optional[Callable[[XPLMWindowID, int, int, int, Any, int], None]]=None, mouse: Optional[Callable[[XPLMWindowID, int, int, XPLMMouseStatus, Any], int]]=None, refCon: Any=None) -> XPLMWindowID: ...
    def destroyWindow(self, windowID: XPLMWindowID) -> None: ...
    def getScreenSize(self) -> tuple[int, int]: ...
    def getScreenBoundsGlobal(self) -> tuple[int, int, int, int]: ...
    def getAllMonitorBoundsGlobal(self, bounds: Callable[[int, int, int, int, int, Any], None], refCon: Any) -> None: ...
    def getAllMonitorBoundsOS(self, bounds: Callable[[int, int, int, int, int, Any], None], refCon: Any) -> None: ...
    def getMouseLocation(self) -> None | tuple[int, int]: ...
    def getMouseLocationGlobal(self) -> None | tuple[int, int]: ...
    def getWindowGeometry(self, windowID: XPLMWindowID) -> None | tuple[int, int, int, int]: ...
    def getAvionicsGeometry(self, avionicsID: XPLMAvionicsID) -> tuple[int, int, int, int]: ...
    def setWindowGeometry(self, windowID: XPLMWindowID, left: int, top: int, right: int, bottom: int) -> None: ...
    def setAvionicsGeometry(self, avionicsID: XPLMAvionicsID, left: int, top: int, right: int, bottom: int) -> None: ...
    def getWindowGeometryOS(self, windowID: XPLMWindowID) -> None | tuple[int, int, int, int]: ...
    def getAvionicsGeometryOS(self, avionicsID: XPLMAvionicsID) -> tuple[int, int, int, int]: ...
    def setAvionicsGeometryOS(self, avionicsID: XPLMAvionicsID, left: int, top: int, right: int, bottom: int) -> None: ...
    def setWindowGeometryOS(self, windowID: XPLMWindowID, left: int, top: int, right: int, bottom: int) -> None: ...
    def getWindowGeometryVR(self, windowID: XPLMWindowID) -> None | tuple[int, int]: ...
    def setWindowGeometryVR(self, windowID: XPLMWindowID, width: int, height: int) -> None: ...
    def getWindowIsVisible(self, windowID: XPLMWindowID) -> int: ...
    def setWindowIsVisible(self, windowID: XPLMWindowID, visible: int=1) -> None: ...
    def windowIsPoppedOut(self, windowID: XPLMWindowID) -> int: ...
    def windowIsInVR(self, windowID: XPLMWindowID) -> int: ...
    def setWindowGravity(self, windowID: XPLMWindowID, left: int, top: int, right: int, bottom: int) -> None: ...
    def setWindowResizingLimits(self, windowID: XPLMWindowID, minWidth: int=0, minHeight: int=0, maxWidth: int=10000, maxHeight: int=10000) -> None: ...
    def setWindowPositioningMode(self, windowID: XPLMWindowID, mode: XPLMWindowPositioningMode, index: int=-1) -> None: ...
    def setWindowTitle(self, windowID: XPLMWindowID, title: str) -> None: ...
    def getWindowRefCon(self, windowID: XPLMWindowID) -> Any: ...
    def setWindowRefCon(self, windowID: XPLMWindowID, refCon: Any) -> None: ...
    def takeKeyboardFocus(self, windowID: XPLMWindowID) -> None: ...
    def hasKeyboardFocus(self, windowID: XPLMWindowID) -> int: ...
    def bringWindowToFront(self, windowID: XPLMWindowID) -> None: ...
    def isWindowInFront(self, windowID: XPLMWindowID) -> int: ...
    def registerHotKey(self, vkey: int, flags: XPLMKeyFlags=NoFlag, description: str='', hotKey: Optional[Callable[[Any], None]]=None, refCon: Any=None) -> XPLMHotKeyID: ...
    def unregisterHotKey(self, hotKeyID: XPLMHotKeyID) -> None: ...
    def countHotKeys(self) -> int: ...
    def getNthHotKey(self, index: int) -> XPLMHotKeyID: ...
    def getHotKeyInfo(self, hotKeyID: XPLMHotKeyID) -> None | HotKeyInfo: ...
    def setHotKeyCombination(self, hotKeyID: XPLMHotKeyID, vKey: int, flags: XPLMKeyFlags=NoFlag) -> None: ...
    def getDrawCallbackDict(self) -> dict[int, tuple[str, Callable, int, int, Any]]: ...
    def getWindowCallbackDict(self) -> dict[XPLMWindowID, tuple[Callable, Callable, Callable, Callable, Callable, Callable, Any, str]]: ...
    def getAvionicsCallbackDict(self) -> dict[XPLMAvionicsID, tuple]: ...
    def getKeySnifferCallbackDict(self) -> dict[int, tuple]: ...
    def getHotKeyCallbackDict(self) -> dict[XPLMHotKeyID, tuple]: ...
    def setGraphicsState(self, fog: int=0, numberTexUnits: int=0, lighting: int=0, alphaTesting: int=0, alphaBlending: int=0, depthTesting: int=0, depthWriting: int=0) -> None: ...
    def bindTexture2d(self, textureID: int, textureUnit: int) -> None: ...
    def generateTextureNumbers(self, count: int=1) -> None | list[int]: ...
    def worldToLocal(self, lat: float, lon: float, alt: float=0.0) -> tuple[float, float, float]: ...
    def localToWorld(self, x: float, y: float, z: float) -> tuple[float, float, float]: ...
    def drawTranslucentDarkBox(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def drawString(self, rgb: Sequence[float]=(1.0, 1.0, 1.0), x: int=0, y: int=0, value: str='', wordWrapWidth: Optional[int]=None, fontID: XPLMFontID=Font_Proportional) -> None: ...
    def drawNumber(self, rgb: Sequence[float]=(1.0, 1.0, 1.0), x: int=0, y: int=0, value: float=0.0, digits: int=-1, decimals: int=0, showSign: int=1, fontID: XPLMFontID=Font_Proportional) -> None: ...
    def getFontDimensions(self, fontID: XPLMFontID) -> None | tuple[int, int, int]: ...
    def measureString(self, fontID: XPLMFontID, string: str) -> float: ...
    def getTexture(self, textureID: XPLMTextureID) -> int: ...
    def createInstance(self, obj: XPLMObjectRef, dataRefs: Optional[tuple[str, ...]]=None) -> XPLMInstanceRef: ...
    def destroyInstance(self, instance: XPLMInstanceRef) -> None: ...
    def instanceSetAutoShift(self, instance: XPLMInstanceRef) -> None: ...
    def instanceSetPosition(self, instance: XPLMInstanceRef, position: XPLMDrawInfo_t | tuple[float, float, float, float, float, float], data: Optional[tuple[float, ...]]=None) -> None: ...
    def instanceSetPositionDouble(self, instance: XPLMInstanceRef, position: XPLMDrawInfoDouble_t | tuple[float, float, float, float, float, float], data: Optional[tuple[float, ...]]=None) -> None: ...
    def createMapLayer(self, mapType: str=MAP_USER_INTERFACE, layerType: XPLMMapLayerType=MapLayer_Markings, delete: Optional[Callable[[XPLMMapLayerID, Any], None]]=None, prep: Optional[Callable[[XPLMMapLayerID, float, XPLMMapProjectionID, Any], None]]=None, draw: Optional[Callable[[XPLMMapLayerID, float, float, float, XPLMMapStyle, XPLMMapProjectionID, Any], None]]=None, icon: Optional[Callable[[XPLMMapLayerID, float, float, float, XPLMMapStyle, XPLMMapProjectionID, Any], None]]=None, label: Optional[Callable[[XPLMMapLayerID, float, float, float, XPLMMapStyle, XPLMMapProjectionID, Any], None]]=None, showToggle: int=1, name: str='', refCon: Any=None) -> XPLMMapLayerID: ...
    def destroyMapLayer(self, layerID: XPLMMapLayerID) -> int: ...
    def registerMapCreationHook(self, mapCreated: Callable[[str, Any], None], refCon: Any=None) -> None: ...
    def mapExists(self, mapType: str) -> int: ...
    def drawMapIconFromSheet(self, layerID: XPLMMapLayerID, png: str, s: int, t: int, ds: int, dt: int, x: float, y: float, orientation: XPLMMapOrientation, rotationDegrees: float, mapWidth: float) -> None: ...
    def drawMapLabel(self, layerID: XPLMMapLayerID, text: str, x: float, y: float, orientation: XPLMMapOrientation, rotationDegrees: float) -> None: ...
    def mapProject(self, projection: XPLMMapProjectionID, latitude: float, longitude: float) -> None | tuple[float, float]: ...
    def mapUnproject(self, projection: XPLMMapProjectionID, x: float, y: float) -> None | tuple[float, float]: ...
    def mapScaleMeter(self, projection: XPLMMapProjectionID, x: float, y: float) -> float: ...
    def mapGetNorthHeading(self, projection: XPLMMapProjectionID, x: float, y: float) -> float: ...
    def getMapCallbackDict(self) -> dict: ...
    def findPluginsMenu(self) -> XPLMMenuID: ...
    def findAircraftMenu(self) -> XPLMMenuID: ...
    def createMenu(self, name: Optional[str]=None, parentMenuID: Optional[XPLMMenuID]=None, parentItem: Optional[int]=0, handler: Optional[Callable[[Any, Any], None]]=None, refCon: Optional[Any]=None) -> None | XPLMMenuID: ...
    def destroyMenu(self, menuID: XPLMMenuID) -> None: ...
    def clearAllMenuItems(self, menuID: Optional[XPLMMenuID]) -> None: ...
    def appendMenuItem(self, menuID: Optional[XPLMMenuID]=None, name: str='Item', refCon: Any=None) -> int: ...
    def appendMenuItemWithCommand(self, menuID: Optional[XPLMMenuID]=None, name: str='Command', commandRef: Any=None) -> int: ...
    def appendMenuSeparator(self, menuID: XPLMMenuID=None) -> None | int: ...
    def setMenuItemName(self, menuID: Optional[XPLMMenuID]=None, index: int=0, name: str='New Name') -> None: ...
    def checkMenuItem(self, menuID: Optional[XPLMMenuID]=None, index: int=0, checked: XPLMMenuCheck=Menu_Checked) -> None: ...
    def checkMenuItemState(self, menuID: Optional[XPLMMenuID], index: int=0) -> int: ...
    def enableMenuItem(self, menuID: Optional[XPLMMenuID]=None, index: int=0, enabled: int=1) -> None: ...
    def removeMenuItem(self, menuID: Optional[XPLMMenuID]=None, index: int=0) -> None: ...
    def getMenuCallbackDict(self) -> dict: ...
    def getFirstNavAid(self) -> int: ...
    def getNextNavAid(self, navRef: XPLMNavRef) -> int: ...
    def findFirstNavAidOfType(self, navType: XPLMNavType) -> int: ...
    def findLastNavAidOfType(self, navType: XPLMNavType) -> int: ...
    def findNavAid(self, name: Optional[str], navAidID: Optional[str], lat: Optional[float], lon: Optional[float], freq: Optional[int], navType: XPLMNavType=Nav_Any) -> XPLMNavRef: ...
    def getNavAidInfo(self, navRef: XPLMNavRef) -> NavAidInfo: ...
    def countFMSEntries(self) -> int: ...
    def getDisplayedFMSEntry(self) -> int: ...
    def getDestinationFMSEntry(self) -> int: ...
    def setDisplayedFMSEntry(self, index: int) -> None: ...
    def setDestinationFMSEntry(self, index: int) -> None: ...
    def getFMSEntryInfo(self, index: int) -> FMSEntryInfo: ...
    def setFMSEntryInfo(self, index: int, navRef: XPLMNavRef, altitude: int=0) -> None: ...
    def setFMSEntryLatLon(self, index: int, lat: float, lon: float, altitude: int=0) -> None: ...
    def clearFMSEntry(self, index: int) -> None: ...
    def getGPSDestinationType(self) -> int: ...
    def getGPSDestination(self) -> int: ...
    def countFMSFlightPlanEntries(self, flightPlan: XPLMNavFlightPlan) -> int: ...
    def getDisplayedFMSFlightPlanEntry(self, flightPlan: XPLMNavFlightPlan) -> int: ...
    def getDestinationFMSFlightPlanEntry(self, flightPlan: XPLMNavFlightPlan) -> int: ...
    def setDisplayedFMSFlightPlanEntry(self, flightPlan: XPLMNavFlightPlan, index: int) -> None: ...
    def setDestinationFMSFlightPlanEntry(self, flightPlan: XPLMNavFlightPlan, index: int) -> None: ...
    def setDirectToFMSFlightPlanEntry(self, flightPlan: XPLMNavFlightPlan, index: int) -> None: ...
    def getFMSFlightPlanEntryInfo(self, flightPlan: XPLMNavFlightPlan, index: int) -> FMSEntryInfo: ...
    def setFMSFlightPlanEntryInfo(self, flightPlan: XPLMNavFlightPlan, index: int, navRef: XPLMNavRef, altitude: int=0) -> None: ...
    def setFMSFlightPlanEntryLatLon(self, flightPlan: XPLMNavFlightPlan, index: int, lat: float, lon: float, altitude: int=0) -> None: ...
    def setFMSFlightPlanEntryLatLonWithId(self, flightPlan: XPLMNavFlightPlan, index: int, lat: float, lon: float, altitude: int=0, ID: str=None) -> None: ...
    def clearFMSFlightPlanEntry(self, flightPlan: XPLMNavFlightPlan, index: int) -> None: ...
    def loadFMSFlightPlan(self, device: int, plan: str) -> None: ...
    def saveFMSFlightPlan(self, device: Optional[int]=0) -> str: ...
    def setUsersAircraft(self, path: str) -> None: ...
    def placeUserAtAirport(self, code: str) -> None: ...
    def placeUserAtLocation(self, latitude: float, longitude: float, elevation: float, heading: float, speed: float) -> None: ...
    def countAircraft(self) -> tuple[int, int, XPLMPluginID]: ...
    def getNthAircraftModel(self, index: int) -> tuple[str, str]: ...
    def acquirePlanes(self, aircraft: Optional[Sequence[str]]=None, callback: Optional[Callable[[Any], None]]=None, refCon: Any=None) -> int: ...
    def releasePlanes(self) -> None: ...
    def setActiveAircraftCount(self, count: int) -> None: ...
    def setAircraftModel(self, index: int, path: str) -> None: ...
    def disableAIForPlane(self, index: int) -> None: ...
    def getMyID(self) -> int: ...
    def countPlugins(self) -> int: ...
    def getNthPlugin(self, index: int) -> XPLMPluginID: ...
    def findPluginByPath(self, path: str) -> XPLMPluginID: ...
    def findPluginBySignature(self, signature: str) -> XPLMPluginID: ...
    def getPluginInfo(self, pluginID: XPLMPluginID) -> PluginInfo: ...
    def isPluginEnabled(self, pluginID: XPLMPluginID) -> int: ...
    def enablePlugin(self, pluginID: XPLMPluginID) -> int: ...
    def disablePlugin(self, pluginID: XPLMPluginID) -> None: ...
    def reloadPlugins(self) -> None: ...
    def sendMessageToPlugin(self, pluginID: XPLMPluginID, message: int, param: Optional[Any]) -> None: ...
    def hasFeature(self, feature: str) -> int: ...
    def isFeatureEnabled(self, feature: str) -> int: ...
    def enableFeature(self, feature: str, enable: int=1) -> None: ...
    def enumerateFeatures(self, enumerator: Callable[[str, Any], None], refCon: Any=None) -> None: ...
    def getElapsedTime(self) -> float: ...
    def getCycleNumber(self) -> int: ...
    def registerFlightLoopCallback(self, callback: Callable[[float, float, int, Any], float], interval: float=0.0, refCon: Any=None) -> None: ...
    def unregisterFlightLoopCallback(self, callback: Callable[[float, float, int, Any], float], refCon: Any=None) -> None: ...
    def setFlightLoopCallbackInterval(self, callback: Callable[[float, float, int, Any], float], interval: float=0.0, relativeToNow: int=1, refCon: Any=None) -> None: ...
    def createFlightLoop(self, callback: Callable[[float, float, int, Any], float], phase: XPLMFlightLoopPhaseType=FlightLoop_Phase_BeforeFlightModel, refCon: Any=None) -> XPLMFlightLoopID: ...
    def isFlightLoopValid(self, flightLoopID: XPLMFlightLoopID) -> bool: ...
    def destroyFlightLoop(self, flightLoopID: XPLMFlightLoopID) -> None: ...
    def scheduleFlightLoop(self, flightLoopID: XPLMFlightLoopID, interval: float=0.0, relativeToNow: int=1) -> None: ...
    def createProbe(self, probeType: XPLMProbeType=ProbeY) -> XPLMProbeRef: ...
    def destroyProbe(self, probe: XPLMProbeRef) -> None: ...
    def probeTerrainXYZ(self, probeRef: XPLMProbeRef, x: float, y: float, z: float) -> XPLMProbeInfo_t: ...
    def getMagneticVariation(self, latitude: float, longitude: float) -> float: ...
    def degTrueToDegMagnetic(self, degrees: float=0.0) -> float: ...
    def degMagneticToDegTrue(self, degrees: float=0.0) -> float: ...
    def loadObject(self, path: str) -> XPLMObjectRef: ...
    def loadObjectAsync(self, path: str, loaded: Callable[[XPLMObjectRef, Any], None], refCon: Any=None) -> None: ...
    def unloadObject(self, objectRef: XPLMObjectRef) -> None: ...
    def lookupObjects(self, path: str, latitude: float=0.0, longitude: float=0.0, enumerator: Optional[Callable[[str, Any], None]]=None, refCon: Any=None) -> int: ...
    def getFMODStudio(self) -> FMOD_STUDIO_SYSTEM: ...
    def getFMODChannelGroup(self, audioType: XPLMAudioBus) -> FMOD_CHANNELGROUP: ...
    def playPCMOnBus(self, audioBuffer: Any, bufferSize: int, soundFormat: int, freqHz: int, numChannels: int, loop: int=0, audioType: XPLMAudioBus=AudioUI, callback: Optional[Callable[[Any, int], None]]=None, refCon: Any=None) -> None | FMODChannel: ...
    def stopAudio(self, channel: FMOD_CHANNEL) -> int: ...
    def setAudioPosition(self, channel: FMOD_CHANNEL, position: Sequence[float], velocity: Optional[Sequence[float]]=None) -> int: ...
    def setAudioFadeDistance(self, channel: FMOD_CHANNEL, min_distance: float=1.0, max_distance: float=10000.0) -> int: ...
    def setAudioVolume(self, channel: FMOD_CHANNEL, volume: float=1.0) -> int: ...
    def setAudioPitch(self, channel: FMOD_CHANNEL, pitch: float=1.0) -> int: ...
    def setAudioCone(self, channel: FMOD_CHANNEL, inside_angle: float=360.0, outside_angle: float=360.0, outside_volume: float=1.0, orientation: Optional[tuple[float, float, float]]=None) -> int: ...
    def speakString(self, string: str) -> None: ...
    def getVirtualKeyDescription(self, vKey: int) -> str: ...
    def reloadScenery(self) -> None: ...
    def getSystemPath(self) -> str: ...
    def getPrefsPath(self) -> str: ...
    def getDirectorySeparator(self) -> str: ...
    def extractFileAndPath(self, fullPath: str) -> tuple[str, str]: ...
    def getDirectoryContents(self, dir: str, firstReturn: int=0, bufSize: int=2048, maxFiles: int=100) -> tuple[int, list[str], int]: ...
    def getVersions(self) -> tuple[int, int, int]: ...
    def getLanguage(self) -> int: ...
    def debugString(self, string: str) -> None: ...
    def setErrorCallback(self, callback: Callable[[str], None]) -> None: ...
    def findSymbol(self, symbol: str) -> int: ...
    def loadDataFile(self, fileType: XPLMDataFileType, path: str) -> int: ...
    def saveDataFile(self, fileType: XPLMDataFileType, path: str) -> int: ...
    def findCommand(self, name: str) -> XPLMCommandRef: ...
    def commandBegin(self, commandRef: XPLMCommandRef) -> None: ...
    def commandEnd(self, commandRef: XPLMCommandRef) -> None: ...
    def commandOnce(self, commandRef: XPLMCommandRef) -> None: ...
    def createCommand(self, name: str, description: Optional[str]=None) -> XPLMCommandRef: ...
    def registerCommandHandler(self, commandRef: XPLMCommandRef, callback: Callable[[XPLMCommandRef, XPLMCommandPhase, Any], int], before: int=1, refCon: Any=None) -> None: ...
    def unregisterCommandHandler(self, commandRef: XPLMCommandRef, callback: Callable[[XPLMCommandRef, XPLMCommandPhase, Any], int], before: int=1, refCon: Any=None) -> None: ...
    def getMETARForAirport(self, airport_id: str) -> str: ...
    def getWeatherAtLocation(self, latitude: float, longitude: float, altitude_m: float) -> None | XPLMWeatherInfo_t: ...
    def beginWeatherUpdate(self) -> None: ...
    def endWeatherUpdate(self, isIncremental: int=1, updateImmediately: int=0) -> None: ...
    def setWeatherAtLocation(self, latitude: float, longitude: float, altitude_m: float, info: XPLMWeatherInfo_t) -> None: ...
    def setWeatherAtAirport(self, airport_id: str, info: XPLMWeatherInfo_t) -> None: ...
    def eraseWeatherAtLocation(self, latitude: float, longitude: float) -> None: ...
    def eraseWeatherAtAirport(self, airport_id: str) -> None: ...
    def reloadPlugin(self, signature: str) -> None: ...
    def getPluginStats(self) -> dict: ...
    def pythonGetDicts(self) -> dict: ...
    def log(self, s: Optional[str]=None) -> None: ...
    def systemLog(self, s: Optional[str]=None) -> None: ...
    def getCapsuleDict(self) -> dict: ...
    def getCapsulePtr(self, capsule_type: str, capsule: Any) -> int: ...
    def getSelfModuleName(self) -> str: ...
    def getPluginDict(self) -> dict: ...
    def drawWindow(self, left: int, bottom: int, right: int, top: int, style: XPWindowStyle=Window_MainWindow) -> None: ...
    def getWindowDefaultDimensions(self, style: XPWindowStyle=Window_MainWindow) -> tuple[int, int]: ...
    def drawElement(self, left: int, bottom: int, right: int, top: int, style: XPElementStyle, lit: int=0) -> None: ...
    def getElementDefaultDimensions(self, style: XPElementStyle) -> tuple[int, int, int]: ...
    def drawTrack(self, left: int, bottom: int, right: int, top: int, minValue: int, maxValue: int, value: int, style: XPTrackStyle, lit: int=0) -> None: ...
    def getTrackDefaultDimensions(self, style: XPTrackStyle) -> tuple[int, int]: ...
    def getTrackMetrics(self, left: int, bottom: int, right: int, top: int, minValue: int, maxValue: int, value: int, style: XPTrackStyle) -> TrackMetrics: ...
    def createWidgets(self, widgetDefs: Sequence[Sequence[Any]], parentID: Optional[XPWidgetID]) -> None | list[XPWidgetID]: ...
    def moveWidgetBy(self, widgetID: XPWidgetID, dx: int=0, dy: int=0) -> None: ...
    def fixedLayout(self, message: XPWidgetMessage, widgetID: XPWidgetID, param1: int, param2: int) -> int: ...
    def selectIfNeeded(self, message: XPWidgetMessage, widgetID: XPWidgetID, param1: int, param2: int, eatClick: int=1) -> int: ...
    def defocusKeyboard(self, message: XPWidgetMessage, widgetID: XPWidgetID, param1: int, param2: int, eatClick: int=1) -> int: ...
    def dragWidget(self, message: XPWidgetMessage, widgetID: XPWidgetID, param1: int, param2: int, left: int, top: int, right: int, bottom: int) -> int: ...
    def createWidget(self, left: int, top: int, right: int, bottom: int, visible: int, descriptor: str, isRoot: int, container: XPWidgetID | Literal[0], widgetClass: XPWidgetClass) -> XPWidgetID: ...
    def createCustomWidget(self, left: int, top: int, right: int, bottom: int, visible: int, descriptor: str, isRoot: int, container: Optional[XPWidgetID], callback: Callable[[XPWidgetMessage, XPWidgetID, int, int], int]) -> XPWidgetID: ...
    def destroyWidget(self, widgetID: XPWidgetID, destroyChildren: int=1) -> None: ...
    def sendMessageToWidget(self, widgetID: XPWidgetID, message: XPWidgetMessage | int, dispatchMode: XPDispatchMode=Mode_UpChain, param1: int=0, param2: int=0) -> int: ...
    def placeWidgetWithin(self, widgetID: XPWidgetID, container: XPWidgetID | Literal[0]=0) -> None: ...
    def countChildWidgets(self, widgetID: XPWidgetID) -> int: ...
    def getNthChildWidget(self, widgetID: XPWidgetID, index: int) -> XPWidgetID: ...
    def getParentWidget(self, widgetID: XPWidgetID) -> XPWidgetID: ...
    def showWidget(self, widgetID: XPWidgetID) -> None: ...
    def hideWidget(self, widgetID: XPWidgetID) -> None: ...
    def isWidgetVisible(self, widgetID: XPWidgetID) -> int: ...
    def findRootWidget(self, widgetID: XPWidgetID) -> XPWidgetID: ...
    def bringRootWidgetToFront(self, widgetID: XPWidgetID) -> None: ...
    def isWidgetInFront(self, widgetID: XPWidgetID) -> int: ...
    def getWidgetGeometry(self, widgetID: XPWidgetID) -> tuple[int, int, int, int]: ...
    def setWidgetGeometry(self, widgetID: XPWidgetID, left: int, top: int, right: int, bottom: int) -> None: ...
    def getWidgetForLocation(self, container: XPWidgetID, xOffset: int, yOffset: int, recursive: int=1, visibleOnly: int=1) -> XPWidgetID: ...
    def getWidgetExposedGeometry(self, widgetID: XPWidgetID) -> tuple[int, int, int, int]: ...
    def setWidgetDescriptor(self, widgetID: XPWidgetID, descriptor: str) -> None: ...
    def getWidgetDescriptor(self, widgetID: XPWidgetID) -> str: ...
    def getWidgetUnderlyingWindow(self, widgetID: XPWidgetID) -> XPLMWindowID: ...
    def setWidgetProperty(self, widgetID: XPWidgetID, propertyID: XPWidgetPropertyID | int, value: Optional[Any]) -> None: ...
    def getWidgetProperty(self, widgetID: XPWidgetID, propertyID: XPWidgetPropertyID | int, exists: int=-1) -> Any: ...
    def setKeyboardFocus(self, widgetID: XPWidgetID) -> int: ...
    def loseKeyboardFocus(self, widgetID: XPWidgetID) -> None: ...
    def getWidgetWithFocus(self) -> XPWidgetID: ...
    def addWidgetCallback(self, widgetID: XPWidgetID, callback: Callable[[XPWidgetMessage, XPWidgetID, int, int], int]) -> None: ...
    def getWidgetClassFunc(self, widgetClass: XPWidgetClass) -> int: ...
    def getWidgetCallbackDict(self) -> dict: ...
    def getWidgetPropertiesDict(self) -> dict: ...
    def disablePythonPlugin(self, signature: str) -> None: ...